/*
    TOP configuration module internal header

    TOP configuration module internal header file

    @file       top_int.h
    @ingroup    mIDrvSys_TOP
    @note       Nothing

    Copyright   Novatek Microelectronics Corp. 2019.  All rights reserved.
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2 as
    published by the Free Software Foundation.
*/

#ifndef _TOP_INT_REG_H
#define _TOP_INT_REG_H


#if defined(__FREERTOS)

/* rtos */
#include <kwrap/nvt_type.h>
#include "plat/pad.h"
#else

/* linux kernel */
#include <mach/nvt_type.h>
#include <plat/pad.h>
#endif


typedef enum
{
	PCTRL_X_CPU_NTRST,
	PCTRL_X_CPU_TDI,
	PCTRL_X_CPU_TMS,
	PCTRL_X_CPU_TCK,
	PCTRL_X_CPU_TDO,
	PCTRL_X_SPI_SCK,
	PCTRL_X_SPI_CSN0,
	PCTRL_X_SPI_TX,

	PCTRL_X_SPI_RX,
	PCTRL_X_SPI_WPN,
	PCTRL_X_SPI_HOLDN,
	PCTRL_X_SPI_CSN1,
	PCTRL_X_SPI_RST,
	PCTRL_X_UART0_SOUT,
	PCTRL_X_UART0_SIN,
	PCTRL_X_UART0_RTS,

	PCTRL_X_UART0_CTS,
	PCTRL_X_UART1_SOUT,
	PCTRL_X_UART1_SIN,
	PCTRL_X_UART2_SOUT,
	PCTRL_X_UART2_SIN,
	PCTRL_X_I2C0_SCL,
	PCTRL_X_I2C0_SDA,
	PCTRL_X_I2C1_SCL,

	PCTRL_X_I2C1_SDA,
	PCTRL_X_I2C2_SCL,
	PCTRL_X_I2C2_SDA,
	PCTRL_X_I2S0_SCLK,
	PCTRL_X_I2S0_FS,
	PCTRL_X_I2S0_RXD,
	PCTRL_X_I2S0_TXD,
	PCTRL_X_I2S1_SCLK,

	PCTRL_X_I2S1_FS,
	PCTRL_X_I2S1_RXD,
	PCTRL_X_I2S1_TXD,
	PCTRL_X_EXT0_CLK,
	PCTRL_X_EXT1_CLK,
	PCTRL_X_RESET_OUT,
	PCTRL_X_PWM0_OUT,
	PCTRL_X_PWM1_OUT,

	PCTRL_X_GPIO_0 = 64,
	PCTRL_X_GPIO_1,
	PCTRL_X_GPIO_2,
	PCTRL_X_GPIO_3,
	PCTRL_X_GPIO_4,
	PCTRL_X_GPIO_5,
	PCTRL_X_GPIO_6,
	PCTRL_X_GPIO_7,

	PCTRL_X_GPIO_8,
	PCTRL_X_GPIO_9,


	PCTRL_X_CAP0_CLK	= 96,
	PCTRL_X_CAP0_DATA0,
	PCTRL_X_CAP0_DATA1,
	PCTRL_X_CAP0_DATA2,
	PCTRL_X_CAP0_DATA3,
	PCTRL_X_CAP0_DATA4,
	PCTRL_X_CAP0_DATA5,
	PCTRL_X_CAP0_DATA6,

	PCTRL_X_CAP0_DATA7,
	PCTRL_X_CAP1_CLK,
	PCTRL_X_CAP1_DATA0,
	PCTRL_X_CAP1_DATA1,
	PCTRL_X_CAP1_DATA2,
	PCTRL_X_CAP1_DATA3,
	PCTRL_X_CAP1_DATA4,
	PCTRL_X_CAP1_DATA5,

	PCTRL_X_CAP1_DATA6,
	PCTRL_X_CAP1_DATA7,
	PCTRL_X_CAP2_CLK,
	PCTRL_X_CAP2_DATA0,
	PCTRL_X_CAP2_DATA1,
	PCTRL_X_CAP2_DATA2,
	PCTRL_X_CAP2_DATA3,
	PCTRL_X_CAP2_DATA4,

	PCTRL_X_CAP2_DATA5,
	PCTRL_X_CAP2_DATA6,
	PCTRL_X_CAP2_DATA7,
	PCTRL_X_CAP3_CLK,
	PCTRL_X_CAP3_DATA0,
	PCTRL_X_CAP3_DATA1,
	PCTRL_X_CAP3_DATA2,
	PCTRL_X_CAP3_DATA3,

	PCTRL_X_CAP3_DATA4,
	PCTRL_X_CAP3_DATA5,
	PCTRL_X_CAP3_DATA6,
	PCTRL_X_CAP3_DATA7,

	PCTRL_X_EPHY0_REFCLK = 160,
	PCTRL_X_EPHY0_RESET,
	PCTRL_X_RGMII0_RX_CLK,
	PCTRL_X_RGMII0_RX_CTL,
	PCTRL_X_RGMII0_RXD0,
	PCTRL_X_RGMII0_RXD1,
	PCTRL_X_RGMII0_RXD2,
	PCTRL_X_RGMII0_RXD3,

	PCTRL_X_RGMII0_TX_CLK,
	PCTRL_X_RGMII0_TX_CTL,
	PCTRL_X_RGMII0_TXD0,
	PCTRL_X_RGMII0_TXD1,
	PCTRL_X_RGMII0_TXD2,
	PCTRL_X_RGMII0_TXD3,
	PCTRL_X_RGMII0_MDC,
	PCTRL_X_RGMII0_MDIO,

	PCTRL_X_VGA_HS = 192,
	PCTRL_X_VGA_VS,
	PCTRL_X_HDMI0_I2C_SCL,
	PCTRL_X_HDMI0_I2C_SDA,
	PCTRL_X_HDMI0_HPD,


	_PCTRL_VCAP_VI0_MUX = 320,
	_PCTRL_VCAP_VI1_MUX,
	_PCTRL_VCAP_VI2_MUX,
	_PCTRL_VCAP_VI3_MUX,

	_PCTRL_ETH_PHY_SEL = 336,

	PCTRL_X_MAX_PIN,
	PCTRL_X_DUMMY_PIN = 63,// this must be assign to non existed pinmux location.
	ENUM_DUMMY4WORD(PCTRL)
} PCTRL;

struct sw_top_reg {
	const uint32_t offset;
	uint32_t value;
};

struct pinmux_pad_table {
	PCTRL pinmux_pin;
	PAD_PIN pad_pin;
	PAD_PULL pad_value[8];
};

/* List all pad mapping table here
static struct pinmux_pad_table gpio_pad_mapping[] = {
	{PCTRL_X_CPU_NTRST,     PAD_X_CPU_NTRST,     {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CPU_TDI,       PAD_X_CPU_TDI,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP, PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_CPU_TMS,       PAD_X_CPU_TMS,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP, PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_CPU_TCK,       PAD_X_CPU_TCK,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP, PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_CPU_TDO,       PAD_X_CPU_TDO,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP, PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_SPI_SCK,       PAD_X_SPI_SCK,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_CSN0,      PAD_X_SPI_CSN0,      {PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_TX,        PAD_X_SPI_TX,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_RX,        PAD_X_SPI_RX,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_WPN,       PAD_X_SPI_WPN,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLDOWN, PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_HOLDN,     PAD_X_SPI_HOLDN,     {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLDOWN, PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_CSN1,      PAD_X_SPI_CSN1,      {PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_SPI_RST,       PAD_X_SPI_RST,       {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART0_SOUT,    PAD_X_UART0_SOUT,    {PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART0_SIN,     PAD_X_UART0_SIN,     {PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART0_RTS,     PAD_X_UART0_RTS,     {PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART0_CTS,     PAD_X_UART0_CTS,     {PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART1_SOUT,    PAD_X_UART1_SOUT,    {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_UART1_SIN,     PAD_X_UART1_SIN,     {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLDOWN, PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_UART2_SOUT,    PAD_X_UART2_SOUT,    {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_UART2_SIN,     PAD_X_UART2_SIN,     {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2C0_SCL,      PAD_X_I2C0_SCL,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2C0_SDA,      PAD_X_I2C0_SDA,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2C1_SCL,      PAD_X_I2C1_SCL,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_I2C1_SDA,      PAD_X_I2C1_SDA,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2C2_SCL,      PAD_X_I2C2_SCL,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2C2_SDA,      PAD_X_I2C2_SDA,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_NONE,     PAD_NONE},},
	{PCTRL_X_I2S0_SCLK,     PAD_X_I2S0_SCLK,     {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLUP},},
	{PCTRL_X_I2S0_FS,       PAD_X_I2S0_FS,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLUP},},
	{PCTRL_X_I2S0_RXD,      PAD_X_I2S0_RXD,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLUP},},
	{PCTRL_X_I2S0_TXD,      PAD_X_I2S0_TXD,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLUP},},
	{PCTRL_X_I2S1_SCLK,     PAD_X_I2S1_SCLK,     {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_PULLDOWN},},
	{PCTRL_X_I2S1_FS,       PAD_X_I2S1_FS,       {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_PULLDOWN},},
	{PCTRL_X_I2S1_RXD,      PAD_X_I2S1_RXD,      {PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_PULLDOWN},},
	{PCTRL_X_I2S1_TXD,      PAD_X_I2S1_TXD,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_PULLDOWN},},
	{PCTRL_X_EXT0_CLK,      PAD_X_EXT0_CLK,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_EXT1_CLK,      PAD_X_EXT1_CLK,      {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLDOWN, PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_RESET_OUT,     PAD_X_RESET_OUT,     {PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_PWM0_OUT,      PAD_X_PWM0_OUT,      {PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_PWM1_OUT,      PAD_X_PWM1_OUT,      {PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_0,        PAD_X_GPIO_0,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_1,        PAD_X_GPIO_1,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_2,        PAD_X_GPIO_2,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_3,        PAD_X_GPIO_3,        {PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_4,        PAD_X_GPIO_4,        {PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_GPIO_5,        PAD_X_GPIO_5,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_GPIO_6,        PAD_X_GPIO_6,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_GPIO_7,        PAD_X_GPIO_7,        {PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_GPIO_8,        PAD_X_GPIO_8,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_PULLUP, PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_GPIO_9,        PAD_X_GPIO_9,        {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_CAP0_CLK,      PAD_X_CAP0_CLK,      {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA0,    PAD_X_CAP0_DATA0,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_CAP0_DATA1,    PAD_X_CAP0_DATA1,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA2,    PAD_X_CAP0_DATA2,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_CAP0_DATA3,    PAD_X_CAP0_DATA3,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA4,    PAD_X_CAP0_DATA4,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA5,    PAD_X_CAP0_DATA5,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA6,    PAD_X_CAP0_DATA6,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP0_DATA7,    PAD_X_CAP0_DATA7,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP1_CLK,      PAD_X_CAP1_CLK,      {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP1_DATA0,    PAD_X_CAP1_DATA0,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP1_DATA1,    PAD_X_CAP1_DATA1,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP1_DATA2,    PAD_X_CAP1_DATA2,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLDOWN, PAD_NONE},},
	{PCTRL_X_CAP1_DATA3,    PAD_X_CAP1_DATA3,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP1_DATA4,    PAD_X_CAP1_DATA4,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_CAP1_DATA5,    PAD_X_CAP1_DATA5,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_PULLUP,   PAD_NONE},},
	{PCTRL_X_CAP1_DATA6,    PAD_X_CAP1_DATA6,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLDOWN},}.
	{PCTRL_X_CAP1_DATA7,    PAD_X_CAP1_DATA7,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_PULLDOWN},}.
	{PCTRL_X_CAP2_CLK,      PAD_X_CAP2_CLK,      {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA0,    PAD_X_CAP2_DATA0,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA1,    PAD_X_CAP2_DATA1,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA2,    PAD_X_CAP2_DATA2,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA3,    PAD_X_CAP2_DATA3,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA4,    PAD_X_CAP2_DATA4,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA5,    PAD_X_CAP2_DATA5,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA6,    PAD_X_CAP2_DATA6,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP2_DATA7,    PAD_X_CAP2_DATA7,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_CLK,      PAD_X_CAP3_CLK,      {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA0,    PAD_X_CAP3_DATA0,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA1,    PAD_X_CAP3_DATA1,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA2,    PAD_X_CAP3_DATA2,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA3,    PAD_X_CAP3_DATA3,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA4,    PAD_X_CAP3_DATA4,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA5,    PAD_X_CAP3_DATA5,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA6,    PAD_X_CAP3_DATA6,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_CAP3_DATA7,    PAD_X_CAP3_DATA7,    {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_EPHY0_REFCLK,  PAD_X_EPHY0_REFCLK,  {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_EPHY0_RESET,   PAD_X_EPHY0_RESET,   {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RX_CLK, PAD_X_RGMII0_RX_CLK, {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RX_CTL, PAD_X_RGMII0_RX_CTL, {PAD_PULLDOWN, PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RXD0,   PAD_X_RGMII0_RXD0,   {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RXD1,   PAD_X_RGMII0_RXD1,   {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RXD2,   PAD_X_RGMII0_RXD2,   {PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_RXD3,   PAD_X_RGMII0_RXD3,   {PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TX_CLK, PAD_X_RGMII0_TX_CLK, {PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TX_CTL, PAD_X_RGMII0_TX_CTL, {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TXD0,   PAD_X_RGMII0_TXD0,   {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TXD1,   PAD_X_RGMII0_TXD1,   {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TXD2,   PAD_X_RGMII0_TXD2,   {PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_TXD3,   PAD_X_RGMII0_TXD3,   {PAD_PULLDOWN, PAD_NONE,     PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_MDC,    PAD_X_RGMII0_MDC,    {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_RGMII0_MDIO,   PAD_X_RGMII0_MDIO,   {PAD_PULLDOWN, PAD_PULLUP,   PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_VGA_HS,        PAD_X_VGA_HS,        {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_VGA_VS,        PAD_X_VGA_VS,        {PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_HDMI0_I2C_SCL, PAD_X_HDMI0_I2C_SCL, {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_HDMI0_I2C_SDA, PAD_X_HDMI0_I2C_SDA, {PAD_PULLDOWN, PAD_PULLUP,   PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
	{PCTRL_X_HDMI0_HPD,     PAD_X_HDMI0_HPD,     {PAD_PULLDOWN, PAD_PULLDOWN, PAD_NONE,     PAD_NONE,     PAD_NONE,     PAD_NONE,   PAD_NONE,     PAD_NONE},},
};
*/

#endif

