
obj-$(CONFIG_SND_ASOC_INGENIC_DMIC) += asoc-dmic.o
obj-$(CONFIG_SND_ASOC_INGENIC_PCM) += asoc-pcm.o

obj-$(CONFIG_SND_ASOC_PDMA) += asoc-dma.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC) += asoc-aic.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC_I2S) += asoc-i2s.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC_SPDIF) += asoc-spdif.o
