#
# Hisilicon Clock specific Makefile
#

obj-y	+= clk.o clkgate-separated.o clkdivider-hi6220.o

obj-$(CONFIG_ARCH_HI3xxx)	+= clk-hi3620.o
obj-$(CONFIG_ARCH_HIP04)	+= clk-hip04.o
obj-$(CONFIG_ARCH_HIX5HD2)	+= clk-hix5hd2.o
obj-$(CONFIG_COMMON_CLK_HI3519)	+= clk-hi3519.o
obj-$(CONFIG_COMMON_CLK_HI3516A)  += clk-hi3516a.o
obj-$(CONFIG_COMMON_CLK_HI3518EV20X)  += clk-hi3518ev20x.o
obj-$(CONFIG_COMMON_CLK_HI3536DV100)  += clk-hi3536dv100.o
obj-$(CONFIG_COMMON_CLK_HI3521A)  += clk-hi3521a.o
obj-$(CONFIG_COMMON_CLK_HI3531A)  += clk-hi3531a.o
obj-$(CONFIG_COMMON_CLK_HI6220)	+= clk-hi6220.o
obj-$(CONFIG_COMMON_CLK_HI3559AV100)	+= clk-hi3559av100.o
obj-$(CONFIG_RESET_HISI)	+= reset.o
obj-$(CONFIG_STUB_CLK_HI6220)	+= clk-hi6220-stub.o
