#
# Hisilicon Clock specific Makefile
#

obj-y	+= clk.o clkgate-separated.o clkdivider-hi6220.o

obj-$(CONFIG_ARCH_HI3xxx)	+= clk-hi3620.o
obj-$(CONFIG_ARCH_HIP04)	+= clk-hip04.o
obj-$(CONFIG_ARCH_HIX5HD2)	+= clk-hix5hd2.o
obj-$(CONFIG_COMMON_CLK_HI3519)	+= clk-hi3519.o
obj-$(CONFIG_COMMON_CLK_HI3516A)  += clk-hi3516a.o
obj-$(CONFIG_COMMON_CLK_HI3516CV500)  += clk-hi3516cv500.o
obj-$(CONFIG_COMMON_CLK_HI3516DV300)  += clk-hi3516dv300.o
obj-$(CONFIG_COMMON_CLK_HI3556V200)  += clk-hi3556v200.o
obj-$(CONFIG_COMMON_CLK_HI3559V200)  += clk-hi3559v200.o
obj-$(CONFIG_COMMON_CLK_HI3518EV20X)  += clk-hi3518ev20x.o
obj-$(CONFIG_COMMON_CLK_HI3536DV100)  += clk-hi3536dv100.o
obj-$(CONFIG_COMMON_CLK_HI3521A)  += clk-hi3521a.o
obj-$(CONFIG_COMMON_CLK_HI3531A)  += clk-hi3531a.o
obj-$(CONFIG_COMMON_CLK_HI3556AV100)  += clk-hi3556av100.o
obj-$(CONFIG_COMMON_CLK_HI3519AV100)  += clk-hi3519av100.o
obj-$(CONFIG_COMMON_CLK_HI3516EV200)  += clk-hi3516ev200.o
obj-$(CONFIG_COMMON_CLK_HI3516EV300)  += clk-hi3516ev300.o
obj-$(CONFIG_COMMON_CLK_HI3518EV300)  += clk-hi3518ev300.o
obj-$(CONFIG_COMMON_CLK_HI3516DV200)  += clk-hi3516dv200.o
obj-$(CONFIG_COMMON_CLK_HI6220)	+= clk-hi6220.o
obj-$(CONFIG_COMMON_CLK_HI3559AV100)	+= clk-hi3559av100.o
obj-$(CONFIG_RESET_HISI)	+= reset.o
obj-$(CONFIG_STUB_CLK_HI6220)	+= clk-hi6220-stub.o
