#
# Goke Clock specific Makefile
#

obj-y	+= clk.o
obj-$(CONFIG_COMMON_CLK_GK7205V200)  += clk-gk7205v200.o
obj-$(CONFIG_COMMON_CLK_GK7205V300)  += clk-gk7205v300.o
obj-$(CONFIG_COMMON_CLK_GK7202V300)  += clk-gk7202v300.o
obj-$(CONFIG_COMMON_CLK_GK7605V100)  += clk-gk7605v100.o
obj-$(CONFIG_RESET_GOKE)	+= reset.o
