obj-m := nvp6324.o
nvp6324-objs := nvp6324_mipi.o mipi_dev_nvp6324.o jaguar1_video.o jaguar1_coax_protocol.o jaguar1_motion.o jaguar1_video_eq.o jaguar1_mipi.o
#nvp6324-objs := nvp6324_mipi.o mipi_dev_nvp6324.o jaguar1_i2c.o jaguar1_video.o jaguar1_coax_protocol.o jaguar1_motion.o jaguar1_video_eq.o jaguar1_mipi.o

clean:
	@make -C $(KERNEL_PATH) M=$(PWD) clean


