/*
 * DO NOT MODIFY.
 * This file was generated by ms_gen_mvxv_h.py
 */
#define MVXV_HEAD_VER   "4"
#define MVXV_LIB_TYPE   "##"
#define MVXV_CHIP_ID    "I6C#"
#define MVXV_CHANGELIST "g55dda6ca2d"
#define MVXV_COMP_ID    "KL_LX510##"
#define MVXV_EXT        "[BR:infinity6c]"

