#ifndef _KDRV_AI_BUILTIN_H_
#define _KDRV_AI_BUILTIN_H_

#define KDRV_AI_MINI_FOR_FASTBOOT    1 //1:LL only, 0:LL+APP for code size reduced.

#if (KDRV_AI_MINI_FOR_FASTBOOT == 2 || KDRV_AI_MINI_FOR_FASTBOOT == 1)
#define KDRV_AI_MINI_NO_LOCK         0  //0:semaphore enable
#else
#define KDRV_AI_MINI_NO_LOCK         0  //0:semaphore enable
#endif

#if (KDRV_AI_MINI_FOR_FASTBOOT == 1) //FOR NON EXPORT_SYMBOL
#define nvt_ai_is_do_ai_init						nvt_builtin_ai_is_do_ai_init
#define nvt_ai_probe 								nvt_builtin_ai_probe
#define nvt_ai_suspend 								nvt_builtin_ai_suspend
#define nvt_ai_resume 								nvt_builtin_ai_resume
#define nvt_ai_remove 								nvt_builtin_ai_remove
#else
#define nvt_ai_is_do_ai_init						nvt_ai_is_do_ai_init
#define nvt_ai_probe 								nvt_ai_probe
#define nvt_ai_suspend 								nvt_ai_suspend
#define nvt_ai_resume 								nvt_ai_resume
#define nvt_ai_remove 								nvt_ai_remove
#endif

#if (KDRV_AI_MINI_FOR_FASTBOOT == 1) //FOR EXPORT_SYMBOL
#define kdrv_ai_reg_nue_isr_cb              		kdrv_ai_builtin_reg_nue_isr_cb
#define kdrv_ai_reg_nue2_isr_cb              		kdrv_ai_builtin_reg_nue2_isr_cb
#define kdrv_ai_reg_cnn_isr_cb              		kdrv_ai_builtin_reg_cnn_isr_cb
#define nue2_isr									nue2_builtin_isr
#define nue_dma_abort                               nue_builtin_dma_abort
#define cnn_dma_abort                               cnn_builtin_dma_abort
#define nue2_dma_abort                              nue2_builtin_dma_abort
#define nue2_dma_abort_exit                         nue2_builtin_dma_abort_exit
#define kdrv_ai_dma_abort                           kdrv_ai_builtin_dma_abort
#define kdrv_ai_install_id                          kdrv_ai_builtin_install_id
#define kdrv_ai_uninstall_id                        kdrv_ai_builtin_uninstall_id
#define kdrv_ai_init                                kdrv_ai_builtin_init
#define kdrv_ai_drv_get_net_supported_num           kdrv_ai_builtin_drv_get_net_supported_num
#define nue2_init                                   nue2_builtin_init
#define nue2_uninit                                 nue2_builtin_uninit
#define nue2_reset_status                           nue2_builtin_reset_status
#define cnn_get_int_enable                          cnn_builtin_get_int_enable
#define cnn_clr_intr_status                         cnn_builtin_clr_intr_status
#define cnn_get_intr_status                         cnn_builtin_get_intr_status
#define cnn_isenable                                cnn_builtin_isenable
#define cnn_set_dmain_lladdr                        cnn_builtin_set_dmain_lladdr
#define cnn_get_dmain_lladdr                        cnn_builtin_get_dmain_lladdr
#define cnn_set_dmain_lladdr_base                   cnn_builtin_set_dmain_lladdr_base
#define cnn_get_dmain_lladdr_base                   cnn_builtin_get_dmain_lladdr_base
#define cnn_get_engmode                             cnn_builtin_get_engmode
#define cnn_get_kerl_en                             cnn_builtin_get_kerl_en
#define cnn_get_out0type                            cnn_builtin_get_out0type
#define cnn_get_out1type                            cnn_builtin_get_out1type
#define cnn_get_dmaio_addr                          cnn_builtin_get_dmaio_addr
#define cnn_get_intype                              cnn_builtin_get_intype
#define cnn_get_insize                              cnn_builtin_get_insize
#define cnn_get_poolkertype                         cnn_builtin_get_poolkertype
#define cnn_get_localpool_parm                      cnn_builtin_get_localpool_parm
#define cnn_get_globalpool_parm                     cnn_builtin_get_globalpool_parm
#define cnn_init                                    cnn_builtin_init
#define cnn_uninit                                  cnn_builtin_uninit
#define cnn_isr                                     cnn_builtin_isr
#define cnn_set_clock_rate                          cnn_builtin_set_clock_rate
#define cnn_get_clock_rate                          cnn_builtin_get_clock_rate
#define cnn_chk_state_machine                       cnn_builtin_chk_state_machine
#define cnn_change_interrupt                        cnn_builtin_change_interrupt
#define cnn_lock                                    cnn_builtin_lock
#define cnn_unlock                                  cnn_builtin_unlock
#define cnn_open                                    cnn_builtin_open
#define cnn_is_opened                               cnn_builtin_is_opened
#define cnn_close                                   cnn_builtin_close
#define cnn_pause                                   cnn_builtin_pause
#define cnn_start                                   cnn_builtin_start
#define cnn_ll_start                                cnn_builtin_ll_start
#define cnn_ll_pause                                cnn_builtin_ll_pause
#define cnn_isr_start                               cnn_builtin_isr_start
#define cnn_ll_isr_start                            cnn_builtin_ll_isr_start
#define cnn_reset                                   cnn_builtin_reset
#define cnn_clr_all                                 cnn_builtin_clr_all
#define cnn_clr_frameend                            cnn_builtin_clr_frameend
#define cnn_wait_frameend                           cnn_builtin_wait_frameend
#define cnn_clr_ll_frameend                         cnn_builtin_clr_ll_frameend
#define cnn_wait_ll_frameend                        cnn_builtin_wait_ll_frameend
#define cnn_set_para2eng                            cnn_builtin_set_para2eng
#define cnn_setmode                                 cnn_builtin_setmode
#define cnn_ll_setmode                              cnn_builtin_ll_setmode
#define cnn_create_resource                         cnn_builtin_create_resource
#define cnn_release_resource                        cnn_builtin_release_resource
#define cnn_set_base_addr                           cnn_builtin_set_base_addr
#define cnn_get_base_addr                           cnn_builtin_get_base_addr
#define cnn_reset_status                            cnn_builtin_reset_status
#define kdrv_ai_roipool_trig                        kdrv_ai_builtin_roipool_trig
#define kdrv_ai_svm_trig                            kdrv_ai_builtin_svm_trig
#define kdrv_ai_reorg_done                          kdrv_ai_builtin_reorg_done
#define kdrv_ai_permute_trig                        kdrv_ai_builtin_permute_trig
#define kdrv_ai_neural_trig                         kdrv_ai_builtin_neural_trig
#define kdrv_ai_fc_trig                             kdrv_ai_builtin_fc_trig
#define kdrv_ai_roipool_done                        kdrv_ai_builtin_roipool_done
#define kdrv_ai_neural_done                         kdrv_ai_builtin_neural_done
#define kdrv_ai_fc_done                             kdrv_ai_builtin_fc_done
#define kdrv_ai_reorg_trig                          kdrv_ai_builtin_reorg_trig
#define kdrv_ai_svm_done                            kdrv_ai_builtin_svm_done
#define kdrv_ai_permute_done                        kdrv_ai_builtin_permute_done
#define kdrv_ai_softmax_trig                        kdrv_ai_builtin_softmax_trig
#define kdrv_ai_softmax_done                        kdrv_ai_builtin_softmax_done
#define kdrv_ai_anchor_trig                         kdrv_ai_builtin_anchor_trig
#define kdrv_ai_anchor_done                         kdrv_ai_builtin_anchor_done
#define kdrv_ai_preproc_trig                        kdrv_ai_builtin_preproc_trig
#define kdrv_ai_preproc_done                        kdrv_ai_builtin_preproc_done
#define kdrv_ai_cnn_ll_trig                         kdrv_ai_builtin_cnn_ll_trig
#define kdrv_ai_cnn_ll_done                         kdrv_ai_builtin_cnn_ll_done
#define kdrv_ai_nue_ll_trig                         kdrv_ai_builtin_nue_ll_trig
#define kdrv_ai_nue_ll_done                         kdrv_ai_builtin_nue_ll_done
#define kdrv_ai_nue2_ll_trig                        kdrv_ai_builtin_nue2_ll_trig
#define kdrv_ai_nue2_ll_done                        kdrv_ai_builtin_nue2_ll_done
#define kdrv_ai_config_flow                         kdrv_ai_builtin_config_flow
#define kdrv_ai_open                                kdrv_ai_builtin_open
#define kdrv_ai_close                               kdrv_ai_builtin_close
#define kdrv_ai_trigger                             kdrv_ai_builtin_trigger
#define kdrv_ai_waitdone                            kdrv_ai_builtin_waitdone
#define kdrv_ai_reset                               kdrv_ai_builtin_reset
#define kdrv_ai_set                                 kdrv_ai_builtin_set
#define kdrv_ai_get                                 kdrv_ai_builtin_get
#define kdrv_ai_set_ll_base_addr                    kdrv_ai_builtin_set_ll_base_addr
#define kdrv_ai_get_eng_caps                        kdrv_ai_builtin_get_eng_caps
#define kdrv_ai_reset_status                        kdrv_ai_builtin_reset_status
#define kdrv_ai_vmalloc                             kdrv_ai_builtin_vmalloc
#define kdrv_ai_vfree                               kdrv_ai_builtin_vfree
#define nue_get_int_enable                          nue_builtin_get_int_enable
#define nue_clr_intr_status                         nue_builtin_clr_intr_status
#define nue_get_intr_status                         nue_builtin_get_intr_status
#define nue_set_dmain_lladdr                        nue_builtin_set_dmain_lladdr
#define nue_get_dmain_lladdr                        nue_builtin_get_dmain_lladdr
#define nue_set_dmain_lladdr_base                   nue_builtin_set_dmain_lladdr_base
#define nue_get_dmain_lladdr_base                   nue_builtin_get_dmain_lladdr_base
#define nue_get_eltin_mode                          nue_builtin_get_eltin_mode
#define nue_get_eltin_sign                          nue_builtin_get_eltin_sign
#define nue_get_eltout_mode                         nue_builtin_get_eltout_mode
#define nue_set_in_rfh                              nue_builtin_set_in_rfh
#define nue_get_ker                                 nue_builtin_get_ker
#define nue_get_engmode                             nue_builtin_get_engmode
#define nue_get_kerl_en                             nue_builtin_get_kerl_en
#define nue_isenable                                nue_builtin_isenable
#define nue_get_outtype                             nue_builtin_get_outtype
#define nue_get_intype                              nue_builtin_get_intype
#define nue_get_dmao_en                             nue_builtin_get_dmao_en
#define nue_get_svmsize                             nue_builtin_get_svmsize
#define nue_get_dmaio_addr                          nue_builtin_get_dmaio_addr
#define nue_get_roinum                              nue_builtin_get_roinum
#define nue_get_insize                              nue_builtin_get_insize
#define nue_get_in_rfh                              nue_builtin_get_in_rfh
#define nue_get_relu_leaky                          nue_builtin_get_relu_leaky
#define nue_get_relu_shf                            nue_builtin_get_relu_shf
#define nue_get_roipool_standard_kersize            nue_builtin_get_roipool_standard_kersize
#define nue_get_roipool_psroi_kersize               nue_builtin_get_roipool_psroi_kersize
#define nue_get_roipool_ratio                       nue_builtin_get_roipool_ratio
#define nue_get_roipool_shf                         nue_builtin_get_roipool_shf
#define nue_get_rsts                                nue_builtin_get_rsts
#define nue_get_parm                                nue_builtin_get_parm
#define nue_get_reorgshf                            nue_builtin_get_reorgshf
#define nue_get_eltshf                              nue_builtin_get_eltshf
#define nue_get_eltcoef                             nue_builtin_get_eltcoef
#define nue_get_poolkertype                         nue_builtin_get_poolkertype
#define nue_get_localpool_parm                      nue_builtin_get_localpool_parm
#define nue_get_globalpool_parm                     nue_builtin_get_globalpool_parm
#define nue_chk_ker1_overflow                       nue_builtin_chk_ker1_overflow
#define nue_set_dma_disable                         nue_builtin_set_dma_disable
#define nue_get_dma_disable                         nue_builtin_get_dma_disable
#define nue_get_engine_idle                         nue_builtin_get_engine_idle
#define nue_init                                    nue_builtin_init
#define nue_uninit                                  nue_builtin_uninit
#define nue_isr                                     nue_builtin_isr
#define nue_get_clock_rate                          nue_builtin_get_clock_rate
#define nue_chk_state_machine                       nue_builtin_chk_state_machine
#define nue_change_interrupt                        nue_builtin_change_interrupt
#define nue_lock                                    nue_builtin_lock
#define nue_unlock                                  nue_builtin_unlock
#define nue_attach                                  nue_builtin_attach
#define nue_detach                                  nue_builtin_detach
#define nue_set_clock_rate                          nue_builtin_set_clock_rate
#define nue_open                                    nue_builtin_open
#define nue_is_opened                               nue_builtin_is_opened
#define nue_close                                   nue_builtin_close
#define nue_pause                                   nue_builtin_pause
#define nue_start                                   nue_builtin_start
#define nue_ll_pause                                nue_builtin_ll_pause
#define nue_ll_start                                nue_builtin_ll_start
#define nue_isr_start                               nue_builtin_isr_start
#define nue_ll_isr_start                            nue_builtin_ll_isr_start
#define nue_reset                                   nue_builtin_reset
#define nue_clr_all                                 nue_builtin_clr_all
#define nue_clr_frameend                            nue_builtin_clr_frameend
#define nue_wait_frameend                           nue_builtin_wait_frameend
#define nue_clr_ll_frameend                         nue_builtin_clr_ll_frameend
#define nue_wait_ll_frameend                        nue_builtin_wait_ll_frameend
#define nue_set_para2eng                            nue_builtin_set_para2eng
#define nue_set_para2linkedlist                     nue_builtin_set_para2linkedlist
#define nue_setmode                                 nue_builtin_setmode
#define nue_ll_setmode                              nue_builtin_ll_setmode
#define nue_create_resource                         nue_builtin_create_resource
#define nue_release_resource                        nue_builtin_release_resource
#define nue_set_base_addr                           nue_builtin_set_base_addr
#define nue_get_base_addr                           nue_builtin_get_base_addr
#define nue_reset_status                            nue_builtin_reset_status
#else
#define kdrv_ai_reg_nue_isr_cb              		kdrv_ai_reg_nue_isr_cb
#define kdrv_ai_reg_nue2_isr_cb              		kdrv_ai_reg_nue2_isr_cb
#define kdrv_ai_reg_cnn_isr_cb              		kdrv_ai_reg_cnn_isr_cb
#define nue2_isr                                    nue2_isr
#define nue_dma_abort                               nue_dma_abort
#define cnn_dma_abort                               cnn_dma_abort
#define nue2_dma_abort                              nue2_dma_abort
#define nue2_dma_abort_exit                         nue2_dma_abort_exit
#define kdrv_ai_dma_abort                           kdrv_ai_dma_abort
#define kdrv_ai_install_id                          kdrv_ai_install_id
#define kdrv_ai_uninstall_id                        kdrv_ai_uninstall_id
#define kdrv_ai_init                                kdrv_ai_init
#define kdrv_ai_drv_get_net_supported_num           kdrv_ai_drv_get_net_supported_num
#define nue2_init                                   nue2_init
#define nue2_uninit                                 nue2_uninit
#define nue2_reset_status                           nue2_reset_status
#define cnn_get_int_enable                          cnn_get_int_enable
#define cnn_clr_intr_status                         cnn_clr_intr_status
#define cnn_get_intr_status                         cnn_get_intr_status
#define cnn_isenable                                cnn_isenable
#define cnn_set_dmain_lladdr                        cnn_set_dmain_lladdr
#define cnn_get_dmain_lladdr                        cnn_get_dmain_lladdr
#define cnn_set_dmain_lladdr_base                   cnn_set_dmain_lladdr_base
#define cnn_get_dmain_lladdr_base                   cnn_get_dmain_lladdr_base
#define cnn_get_engmode                             cnn_get_engmode
#define cnn_get_kerl_en                             cnn_get_kerl_en
#define cnn_get_out0type                            cnn_get_out0type
#define cnn_get_out1type                            cnn_get_out1type
#define cnn_get_dmaio_addr                          cnn_get_dmaio_addr
#define cnn_get_intype                              cnn_get_intype
#define cnn_get_insize                              cnn_get_insize
#define cnn_get_poolkertype                         cnn_get_poolkertype
#define cnn_get_localpool_parm                      cnn_get_localpool_parm
#define cnn_get_globalpool_parm                     cnn_get_globalpool_parm
#define cnn_init                                    cnn_init
#define cnn_uninit                                  cnn_uninit
#define cnn_isr                                     cnn_isr
#define cnn_set_clock_rate                          cnn_set_clock_rate
#define cnn_get_clock_rate                          cnn_get_clock_rate
#define cnn_chk_state_machine                       cnn_chk_state_machine
#define cnn_change_interrupt                        cnn_change_interrupt
#define cnn_lock                                    cnn_lock
#define cnn_unlock                                  cnn_unlock
#define cnn_open                                    cnn_open
#define cnn_is_opened                               cnn_is_opened
#define cnn_close                                   cnn_close
#define cnn_pause                                   cnn_pause
#define cnn_start                                   cnn_start
#define cnn_ll_start                                cnn_ll_start
#define cnn_ll_pause                                cnn_ll_pause
#define cnn_isr_start                               cnn_isr_start
#define cnn_ll_isr_start                            cnn_ll_isr_start
#define cnn_reset                                   cnn_reset
#define cnn_clr_all                                 cnn_clr_all
#define cnn_clr_frameend                            cnn_clr_frameend
#define cnn_wait_frameend                           cnn_wait_frameend
#define cnn_clr_ll_frameend                         cnn_clr_ll_frameend
#define cnn_wait_ll_frameend                        cnn_wait_ll_frameend
#define cnn_set_para2eng                            cnn_set_para2eng
#define cnn_setmode                                 cnn_setmode
#define cnn_ll_setmode                              cnn_ll_setmode
#define cnn_create_resource                         cnn_create_resource
#define cnn_release_resource                        cnn_release_resource
#define cnn_set_base_addr                           cnn_set_base_addr
#define cnn_get_base_addr                           cnn_get_base_addr
#define cnn_reset_status                            cnn_reset_status
#define kdrv_ai_roipool_trig                        kdrv_ai_roipool_trig
#define kdrv_ai_svm_trig                            kdrv_ai_svm_trig
#define kdrv_ai_reorg_done                          kdrv_ai_reorg_done
#define kdrv_ai_permute_trig                        kdrv_ai_permute_trig
#define kdrv_ai_neural_trig                         kdrv_ai_neural_trig
#define kdrv_ai_fc_trig                             kdrv_ai_fc_trig
#define kdrv_ai_roipool_done                        kdrv_ai_roipool_done
#define kdrv_ai_neural_done                         kdrv_ai_neural_done
#define kdrv_ai_fc_done                             kdrv_ai_fc_done
#define kdrv_ai_reorg_trig                          kdrv_ai_reorg_trig
#define kdrv_ai_svm_done                            kdrv_ai_svm_done
#define kdrv_ai_permute_done                        kdrv_ai_permute_done
#define kdrv_ai_softmax_trig                        kdrv_ai_softmax_trig
#define kdrv_ai_softmax_done                        kdrv_ai_softmax_done
#define kdrv_ai_anchor_trig                         kdrv_ai_anchor_trig
#define kdrv_ai_anchor_done                         kdrv_ai_anchor_done
#define kdrv_ai_preproc_trig                        kdrv_ai_preproc_trig
#define kdrv_ai_preproc_done                        kdrv_ai_preproc_done
#define kdrv_ai_cnn_ll_trig                         kdrv_ai_cnn_ll_trig
#define kdrv_ai_cnn_ll_done                         kdrv_ai_cnn_ll_done
#define kdrv_ai_nue_ll_trig                         kdrv_ai_nue_ll_trig
#define kdrv_ai_nue_ll_done                         kdrv_ai_nue_ll_done
#define kdrv_ai_nue2_ll_trig                        kdrv_ai_nue2_ll_trig
#define kdrv_ai_nue2_ll_done                        kdrv_ai_nue2_ll_done
#define kdrv_ai_config_flow                         kdrv_ai_config_flow
#define kdrv_ai_open                                kdrv_ai_open
#define kdrv_ai_close                               kdrv_ai_close
#define kdrv_ai_trigger                             kdrv_ai_trigger
#define kdrv_ai_waitdone                            kdrv_ai_waitdone
#define kdrv_ai_reset                               kdrv_ai_reset
#define kdrv_ai_set                                 kdrv_ai_set
#define kdrv_ai_get                                 kdrv_ai_get
#define kdrv_ai_set_ll_base_addr                    kdrv_ai_set_ll_base_addr
#define kdrv_ai_get_eng_caps                        kdrv_ai_get_eng_caps
#define kdrv_ai_reset_status                        kdrv_ai_reset_status
#define kdrv_ai_vmalloc                             kdrv_ai_vmalloc
#define kdrv_ai_vfree                               kdrv_ai_vfree
#define nue_get_int_enable                          nue_get_int_enable
#define nue_clr_intr_status                         nue_clr_intr_status
#define nue_get_intr_status                         nue_get_intr_status
#define nue_set_dmain_lladdr                        nue_set_dmain_lladdr
#define nue_get_dmain_lladdr                        nue_get_dmain_lladdr
#define nue_set_dmain_lladdr_base                   nue_set_dmain_lladdr_base
#define nue_get_dmain_lladdr_base                   nue_get_dmain_lladdr_base
#define nue_get_eltin_mode                          nue_get_eltin_mode
#define nue_get_eltin_sign                          nue_get_eltin_sign
#define nue_get_eltout_mode                         nue_get_eltout_mode
#define nue_set_in_rfh                              nue_set_in_rfh
#define nue_get_ker                                 nue_get_ker
#define nue_get_engmode                             nue_get_engmode
#define nue_get_kerl_en                             nue_get_kerl_en
#define nue_isenable                                nue_isenable
#define nue_get_outtype                             nue_get_outtype
#define nue_get_intype                              nue_get_intype
#define nue_get_dmao_en                             nue_get_dmao_en
#define nue_get_svmsize                             nue_get_svmsize
#define nue_get_dmaio_addr                          nue_get_dmaio_addr
#define nue_get_roinum                              nue_get_roinum
#define nue_get_insize                              nue_get_insize
#define nue_get_in_rfh                              nue_get_in_rfh
#define nue_get_relu_leaky                          nue_get_relu_leaky
#define nue_get_relu_shf                            nue_get_relu_shf
#define nue_get_roipool_standard_kersize            nue_get_roipool_standard_kersize
#define nue_get_roipool_psroi_kersize               nue_get_roipool_psroi_kersize
#define nue_get_roipool_ratio                       nue_get_roipool_ratio
#define nue_get_roipool_shf                         nue_get_roipool_shf
#define nue_get_rsts                                nue_get_rsts
#define nue_get_parm                                nue_get_parm
#define nue_get_reorgshf                            nue_get_reorgshf
#define nue_get_eltshf                              nue_get_eltshf
#define nue_get_eltcoef                             nue_get_eltcoef
#define nue_get_poolkertype                         nue_get_poolkertype
#define nue_get_localpool_parm                      nue_get_localpool_parm
#define nue_get_globalpool_parm                     nue_get_globalpool_parm
#define nue_chk_ker1_overflow                       nue_chk_ker1_overflow
#define nue_set_dma_disable                         nue_set_dma_disable
#define nue_get_dma_disable                         nue_get_dma_disable
#define nue_get_engine_idle                         nue_get_engine_idle
#define nue_init                                    nue_init
#define nue_uninit                                  nue_uninit
#define nue_isr                                     nue_isr
#define nue_get_clock_rate                          nue_get_clock_rate
#define nue_chk_state_machine                       nue_chk_state_machine
#define nue_change_interrupt                        nue_change_interrupt
#define nue_lock                                    nue_lock
#define nue_unlock                                  nue_unlock
#define nue_attach                                  nue_attach
#define nue_detach                                  nue_detach
#define nue_set_clock_rate                          nue_set_clock_rate
#define nue_open                                    nue_open
#define nue_is_opened                               nue_is_opened
#define nue_close                                   nue_close
#define nue_pause                                   nue_pause
#define nue_start                                   nue_start
#define nue_ll_pause                                nue_ll_pause
#define nue_ll_start                                nue_ll_start
#define nue_isr_start                               nue_isr_start
#define nue_ll_isr_start                            nue_ll_isr_start
#define nue_reset                                   nue_reset
#define nue_clr_all                                 nue_clr_all
#define nue_clr_frameend                            nue_clr_frameend
#define nue_wait_frameend                           nue_wait_frameend
#define nue_clr_ll_frameend                         nue_clr_ll_frameend
#define nue_wait_ll_frameend                        nue_wait_ll_frameend
#define nue_set_para2eng                            nue_set_para2eng
#define nue_set_para2linkedlist                     nue_set_para2linkedlist
#define nue_setmode                                 nue_setmode
#define nue_ll_setmode                              nue_ll_setmode
#define nue_create_resource                         nue_create_resource
#define nue_release_resource                        nue_release_resource
#define nue_set_base_addr                           nue_set_base_addr
#define nue_get_base_addr                           nue_get_base_addr
#define nue_reset_status                            nue_reset_status
#endif //#if (KDRV_AI_MINI_FOR_FASTBOOT == 1)

#endif
