#
# linux/drivers/mtd/devices/ingenic_sfc_v1/Makefile
#

obj-$(CONFIG_MTD_INGENIC_SFC_V1_NORFLASH)	+= ingenic_sfc_common.o ingenic_sfc_nor.o ingenic_sfc_ops.o
obj-$(CONFIG_MTD_INGENIC_SFC_V1_NANDFLASH)	+= ingenic_sfc_common.o ingenic_sfc_nand.o nand_device/

