/*------------------------------------------------------------------------------
	Copyright (c) 2008 MStar Semiconductor, Inc.  All rights reserved.
------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/

#ifndef __IRQ_CEDRIC_H
#define __IRQ_CEDRIC_H

/*------------------------------------------------------------------------------
    Constant
-------------------------------------------------------------------------------*/
/*
 *  1. Need to use GIC for the SMP & ARM CA9 global timer & ARM TWD timer
 *  2. The GIC pins are not connected correctly in Cedric so the irqchip must be implmeneted
 *  3. Shift the interrupt from 2048
 */


#define INT_START                  2048//to avoid GIC ID
/* FIQ Definition */
#define FIQ_START                  	INT_START
#define INT_FIQ_TIMER0            	(FIQ_START + 0)
#define INT_FIQ_TIMER1            	(FIQ_START + 1)
#define INT_FIQ_WDT                	(FIQ_START + 2)
#define INT_FIQ_TOP1                (FIQ_START + 3)
#define INT_FIQ_TOP0                (FIQ_START + 4)
#define INT_FIQ_DUMMY05             (FIQ_START + 5)
#define INT_FIQ_DUMMY06             (FIQ_START + 6)
#define INT_FIQ_DUMMY07             (FIQ_START + 7)
#define INT_FIQ_USB                	(FIQ_START + 8)
#define INT_FIQ_UHC                	(FIQ_START + 9)
#define INT_FIQ_DUMMY10             (FIQ_START + 10)
#define INT_FIQ_DUMMY11             (FIQ_START + 11)
#define INT_FIQ_DUMMY12             (FIQ_START + 12)
#define INT_FIQ_DUMMY13             (FIQ_START + 13)
#define INT_FIQ_DUMMY14             (FIQ_START + 14)
#define INT_FIQ_TSP2AEON            (FIQ_START + 15)
#define INT_FIQ_DUMMY16             (FIQ_START + 16)
#define INT_FIQ_DUMMY17             (FIQ_START + 17)
#define INT_FIQ_DUMMY18             (FIQ_START + 18)
#define INT_FIQ_XIU_TIME_OUT        (FIQ_START + 19)
#define INT_FIQ_DUMMY20             (FIQ_START + 20)
#define INT_FIQ_VE_F0               (FIQ_START + 21)
#define INT_FIQ_VE_F1               (FIQ_START + 22)
#define INT_FIQ_DUMMY23             (FIQ_START + 23)
#define INT_FIQ_DUMMY24             (FIQ_START + 24)
#define INT_FIQ_VE_VSYNC_IN         (FIQ_START + 25)
#define INT_FIQ_HDMITX_EDGE         (FIQ_START + 26)
#define INT_FIQ_IR                	(FIQ_START + 27)
#define INT_FIQ_AFEC_VSYNC          (FIQ_START + 28)
#define INT_FIQ_DUMMY29             (FIQ_START + 29)
#define INT_FIQ_DUMMY30             (FIQ_START + 30)
#define INT_FIQ_AU_SYSTEM_EDGE      (FIQ_START + 31)
#define INT_FIQ_IR_RC               (FIQ_START + 32)
#define INT_FIQ_DUMMY33             (FIQ_START + 33)
#define INT_FIQ_IR_IN               (FIQ_START + 34)
#define INT_FIQ_DUMMY35             (FIQ_START + 35)
#define INT_FIQ_HST0TO3             (FIQ_START + 36)
#define INT_FIQ_HST0TO2             (FIQ_START + 37)
#define INT_FIQ_HST0TO1             (FIQ_START + 38)
#define INT_FIQ_EXT_GPIO0           (FIQ_START + 39)
#define INT_FIQ_HST1TO3             (FIQ_START + 40)
#define INT_FIQ_HST1TO2             (FIQ_START + 41)
#define INT_FIQ_HST1TO0             (FIQ_START + 42)
#define INT_FIQ_EXT_GPIO1           (FIQ_START + 43)
#define INT_FIQ_HST2TO3             (FIQ_START + 44)
#define INT_FIQ_HST2TO1             (FIQ_START + 45)
#define INT_FIQ_HST2TO0             (FIQ_START + 46)
#define INT_FIQ_EXT_GPIO2           (FIQ_START + 47)
#define INT_FIQ_HST3TO2             (FIQ_START + 48)
#define INT_FIQ_HST3TO1             (FIQ_START + 49)
#define INT_FIQ_HST3TO0             (FIQ_START + 50)
#define INT_FIQ_USB1                (FIQ_START + 51)
#define INT_FIQ_UHC1                (FIQ_START + 52)
#define INT_FIQ_USB2                (FIQ_START + 53)
#define INT_FIQ_UHC2                (FIQ_START + 54)
#define INT_FIQ_EXT_GPIO3           (FIQ_START + 55)
#define INT_FIQ_EXT_GPIO4           (FIQ_START + 56)
#define INT_FIQ_EXT_GPIO5           (FIQ_START + 57)
#define INT_FIQ_EXT_GPIO6           (FIQ_START + 58)
#define INT_FIQ_PWM_RP_L            (FIQ_START + 59)
#define INT_FIQ_PWM_FP_L            (FIQ_START + 60)
#define INT_FIQ_PWM_RP_R            (FIQ_START + 61)
#define INT_FIQ_PWM_FP_R            (FIQ_START + 62)
#define INT_FIQ_EXT_GPIO7           (FIQ_START + 63)
#define FIQ_END						(FIQ_START + 64)


/* IRQ Definition */
#define IRQ_START                  	(FIQ_END)
#define INT_IRQ_UART0             	(IRQ_START + 0)
#define INT_IRQ_PMU                	(IRQ_START + 1)
#define INT_IRQ_ROT                	(IRQ_START + 2)
#define INT_IRQ_MVD                	(IRQ_START + 3)
#define INT_IRQ_DISP2               (IRQ_START + 4)
#define INT_IRQ_OTG                	(IRQ_START + 5)
#define INT_IRQ_USB                	(IRQ_START + 6)
#define INT_IRQ_UHC                	(IRQ_START + 7)
#define INT_IRQ_VP6                	(IRQ_START + 8)
#define INT_IRQ_AUDIO_ATOP          (IRQ_START + 9)
#define INT_IRQ_DISP                (IRQ_START + 10)
#define INT_IRQ_SDIO2RIU            (IRQ_START + 11)
#define INT_IRQ_SDIO1_2RIU          (IRQ_START + 12)
#define INT_IRQ_SDIO2_2RIU          (IRQ_START + 13)
#define INT_IRQ_COMB                (IRQ_START + 14)
#define INT_IRQ_ISP                	(IRQ_START + 15)
#define INT_IRQ_TSP2HK              (IRQ_START + 16)
#define INT_IRQ_AUX_ADCDONE         (IRQ_START + 17)
#define INT_IRQ_AUX_PENDET          (IRQ_START + 18)
#define INT_IRQ_DC               	(IRQ_START + 19)
#define INT_IRQ_GOP                	(IRQ_START + 20)
#define INT_IRQ_RTC                	(IRQ_START + 21)
#define INT_IRQ_COMBO_WDT           (IRQ_START + 22)
#define INT_IRQ_DIPW                (IRQ_START + 23)
#define INT_IRQ_SAR                	(IRQ_START + 24)
#define INT_IRQ_AUX_KEY             (IRQ_START + 25)
#define INT_IRQ_HDMI_TX             (IRQ_START + 26)
#define INT_IRQ_SCM                	(IRQ_START + 27)
#define INT_IRQ_VBI                	(IRQ_START + 28)
#define INT_IRQ_MVD2MIPS            (IRQ_START + 29)
#define INT_IRQ_GPD                	(IRQ_START + 30)
#define INT_IRQ_FCIE                (IRQ_START + 31)
#define INT_IRQ_HVD                	(IRQ_START + 32)
#define INT_IRQ_USB1                (IRQ_START + 33)
#define INT_IRQ_UHC1                (IRQ_START + 34)
#define INT_IRQ_MIU                	(IRQ_START + 35)
#define INT_IRQ_USB2                (IRQ_START + 36)
#define INT_IRQ_UHC2                (IRQ_START + 37)
#define INT_IRQ_AEON2HI             (IRQ_START + 38)
#define INT_IRQ_UART1               (IRQ_START + 39)
#define INT_IRQ_UART2               (IRQ_START + 40)
#define INT_IRQ_UART3               (IRQ_START + 41)
#define INT_IRQ_MPIF                (IRQ_START + 42)
#define INT_IRQ_AU_SYSTEM           (IRQ_START + 43)
#define INT_IRQ_DISP1               (IRQ_START + 44)
#define INT_IRQ_JPD                	(IRQ_START + 45)
#define INT_IRQ_ICP                	(IRQ_START + 46)
#define INT_IRQ_MFE                	(IRQ_START + 47)
#define INT_IRQ_BDMA0               (IRQ_START + 48)
#define INT_IRQ_BDMA1               (IRQ_START + 49)
#define INT_IRQ_FUART0             	(IRQ_START + 50)
#define INT_IRQ_URDMA0              (IRQ_START + 51)
#define INT_IRQ_CMDQ                (IRQ_START + 52)
#define INT_IRQ_G3D2MCU             (IRQ_START + 53)
#define INT_IRQ_CEC                	(IRQ_START + 54)
#define INT_IRQ_SSI                	(IRQ_START + 55)
#define INT_IRQ_FUART1              (IRQ_START + 56)
#define INT_IRQ_COMBO_MISC_TIMER    (IRQ_START + 57)
#define INT_IRQ_COMBO_TIMERS        (IRQ_START + 58)
#define INT_IRQ_GE                	(IRQ_START + 59)
#define INT_IRQ_IIC1_DMA            (IRQ_START + 60)
#define INT_IRQ_IIC1                (IRQ_START + 61)
#define INT_IRQ_IIC0_DMA            (IRQ_START + 62)
#define INT_IRQ_IIC0                (IRQ_START + 63)
#define IRQ_END						(IRQ_START + 64)

#define PMU_START					(IRQ_END)
#define INT_PMU_GPIO00				(PMU_START + 0)
#define INT_PMU_GPIO01				(PMU_START + 1)
#define INT_PMU_GPIO02				(PMU_START + 2)
#define INT_PMU_GPIO03				(PMU_START + 3)
#define INT_PMU_GPIO04				(PMU_START + 4)
#define INT_PMU_GPIO05				(PMU_START + 5)
#define INT_PMU_GPIO06				(PMU_START + 6)
#define INT_PMU_GPIO07				(PMU_START + 7)
#define INT_PMU_GPIO08				(PMU_START + 8)
#define INT_PMU_GPIO09				(PMU_START + 9)
#define INT_PMU_GPIO10				(PMU_START + 10)
#define INT_PMU_GPIO11				(PMU_START + 11)
#define INT_PMU_GPIO12				(PMU_START + 12)
#define INT_PMU_GPIO13				(PMU_START + 13)
#define INT_PMU_GPIO14				(PMU_START + 14)
#define INT_PMU_GPIO15				(PMU_START + 15)
#define INT_PMU_SD_DETECT0			(PMU_START + 16)
#define INT_PMU_SD_DETECT1			(PMU_START + 17)
#define INT_PMU_SD_DETECT2			(PMU_START + 18)
#define INT_PMU_SD_DETECT3			(PMU_START + 19)
#define INT_PMU_DUMMY20				(PMU_START + 20)
#define INT_PMU_KEY0				(PMU_START + 21)
#define INT_PMU_TP					(PMU_START + 22)
#define INT_PMU_RTC					(PMU_START + 23)
#define INT_PMU_IR					(PMU_START + 24)
#define INT_PMU_CEC					(PMU_START + 25)
#define INT_PMU_ONOFF_PULSE			(PMU_START + 26)
#define INT_PMU_KEYOFF_PULSE		(PMU_START + 27)
#define INT_PMU_ADAPTOR_PLUG		(PMU_START + 28)
#define INT_PMU_ADAPTOR_UNPLUG		(PMU_START + 29)
#define INT_PMU_NO_BAT				(PMU_START + 30)
#define INT_PMU_RIU_CKSUM_PROT		(PMU_START + 31)
#define PMU_END						(PMU_START + 32)


#define CEDRIC_NR_IRQS			(PMU_END)

#define CEDRIC_NR_GPIO_IRQ		(32)

//for GIC_ID
#define GIC_ID_LEGACY_FIQ       0x1C
#define GIC_ID_LEGACY_IRQ       0x1F
#define GIC_ID_LOCAL_TIMER_IRQ  0x1D

#endif // __ARCH_ARM_ASM_IRQS_H
