EXTRA_CFLAGS      +=  -Idrivers/mstar/include

# iNfinity3e Platform Support
obj-$(CONFIG_MS_SOUND_INFINITY3) += infinity_dai.o infinity_pcm.o infinity_soc.o infinity_codec.o infinity_dma.o infinity.o





