#
# Makefile for the SPI NAND MTD
#

# Core functionality.
obj-$(CONFIG_MTD_SPINAND)		+= spinand.o
obj-$(CONFIG_MTD_SPINOR)		+= spinor.o
obj-$(CONFIG_MTD_SPI020NAND)		+= spi020_nand.o

#spinand-objs := spinand_mtd.o spinand_lld.o


