obj-y += helix_drv.o
obj-y += default_sliceinfo.o
obj-y += helix_ops.o
#obj-y += helix_ctrl.o
obj-y += api/helix_x264_enc.o
obj-y += api/helix_jpeg_enc.o
obj-y += api/helix_jpeg_dec.o

obj-y += h264enc/set.o
obj-y += h264enc/cabac.o
obj-y += h264enc/common.o
obj-y += h264enc/slice.o

obj-y += h264e.o
obj-y += jpge.o
obj-y += jpgd.o


