#include<linux/module.h>
#include "libfdt_env.h"
#include <fdt.h>
#include <libfdt.h>
#include "libfdt_internal.h"

EXPORT_SYMBOL(fdt_next_node);
EXPORT_SYMBOL(fdt_first_subnode);
EXPORT_SYMBOL(fdt_next_subnode);
EXPORT_SYMBOL(fdt_check_header);
EXPORT_SYMBOL(fdt_move);
EXPORT_SYMBOL(fdt_check_full);
EXPORT_SYMBOL(fdt_get_string);
EXPORT_SYMBOL(fdt_string);
EXPORT_SYMBOL(fdt_get_max_phandle);
EXPORT_SYMBOL(fdt_num_mem_rsv);
EXPORT_SYMBOL(fdt_get_mem_rsv);
EXPORT_SYMBOL(fdt_subnode_offset_namelen);
EXPORT_SYMBOL(fdt_subnode_offset);
EXPORT_SYMBOL(fdt_path_offset_namelen);
EXPORT_SYMBOL(fdt_path_offset);
EXPORT_SYMBOL(fdt_get_name);
EXPORT_SYMBOL(fdt_first_property_offset);
EXPORT_SYMBOL(fdt_next_property_offset);
EXPORT_SYMBOL(fdt_get_property_by_offset);
EXPORT_SYMBOL(fdt_get_property_namelen);
EXPORT_SYMBOL(fdt_get_property);
EXPORT_SYMBOL(fdt_getprop_by_offset);
EXPORT_SYMBOL(fdt_getprop_namelen);
EXPORT_SYMBOL(fdt_getprop);
EXPORT_SYMBOL(fdt_get_phandle);
EXPORT_SYMBOL(fdt_get_alias_namelen);
EXPORT_SYMBOL(fdt_get_alias);
EXPORT_SYMBOL(fdt_get_path);
EXPORT_SYMBOL(fdt_supernode_atdepth_offset);
EXPORT_SYMBOL(fdt_node_depth);
EXPORT_SYMBOL(fdt_parent_offset);
EXPORT_SYMBOL(fdt_node_offset_by_prop_value);
EXPORT_SYMBOL(fdt_node_offset_by_phandle);
EXPORT_SYMBOL(fdt_node_check_compatible);
EXPORT_SYMBOL(fdt_node_offset_by_compatible);
EXPORT_SYMBOL(fdt_stringlist_contains);
EXPORT_SYMBOL(fdt_stringlist_count);
EXPORT_SYMBOL(fdt_stringlist_search);
EXPORT_SYMBOL(fdt_stringlist_get);
EXPORT_SYMBOL(fdt_address_cells);
EXPORT_SYMBOL(fdt_size_cells);
EXPORT_SYMBOL(fdt_setprop_inplace_namelen_partial);
EXPORT_SYMBOL(fdt_setprop_inplace);
EXPORT_SYMBOL(fdt_setprop_inplace_u32);
EXPORT_SYMBOL(fdt_setprop_inplace_u64);
EXPORT_SYMBOL(fdt_setprop_inplace_cell);
EXPORT_SYMBOL(fdt_nop_property);
EXPORT_SYMBOL(fdt_nop_node);
EXPORT_SYMBOL(fdt_strerror);
EXPORT_SYMBOL(fdt_create_empty_tree);
EXPORT_SYMBOL(fdt_setprop);
EXPORT_SYMBOL(fdt_pack);
EXPORT_SYMBOL(fdt_add_subnode);