#
# Makefile for Goke processors family
#

obj-$(CONFIG_ARCH_GK7205V200) += mach-gk7205v200.o
obj-$(CONFIG_ARCH_GK7205V300) += mach-gk7205v300.o
obj-$(CONFIG_ARCH_GK7202V300) += mach-gk7202v300.o
obj-$(CONFIG_ARCH_GK7605V100) += mach-gk7605v100.o
