obj-$(CONFIG_PHY_HISI_SATA)			+= phy-hisi-sata.o
obj-$(CONFIG_PHY_HISI_USB2)			+= phy-hisi-usb.o
obj-$(CONFIG_ARCH_HI3516A)			+= phy-hi3516a-usb.o
obj-$(CONFIG_ARCH_HI3536DV100)		+= phy-hi3536d-usb.o
