
#ifndef   _EMU_USBTEST_H
#define   _EMU_USBTEST_H

//#include "usb2dev_int.h"

#define EMUUSBTEST_ISOC_SIZE    0x200000

#define EMUUSBTEST_DRAM2		DISABLE
#define EMUUSBTEST_WP			DISABLE


#define EMUUSBTEST_FLAG_IDLE1   0x00000001
#define EMUUSBTEST_FLAG_IDLE2   0x00000002
#define EMUUSBTEST_FLAG_EP0_OUT 0x00000004
#define EMUUSBTEST_FLAG_BULK    0x00000008
#define EMUUSBTEST_FLAG_INTR    0x00000010
#define EMUUSBTEST_FLAG_IDLE3   0x00000020
#define EMUUSBTEST_FLAG_INTR_IN 0x00000040
#define EMUUSBTEST_FLAG_BULK_IN 0x00000080
#define EMUUSBTEST_FLAG_ISOC_IN 0x00000100
#define EMUUSBTEST_FLAG_ISOC    0x00000200
#define EMUUSBTEST_FLAG_IDLE4   0x00000400
#define EMUUSBTEST_FLAG_IDLE5   0x00000800
#define EMUUSBTEST_FLAG_UVC1    0x00001000
#define EMUUSBTEST_FLAG_UVC2    0x00002000
#define EMUUSBTEST_FLAG_IDLE6   0x00004000
#define EMUUSBTEST_FLAG_IDLE7   0x00008000


#define EMUUSBTEST_FLAG_RESET   0x80000000

#define USB_BULKIN_EP           USB_EP1
#define USB_BULKOUT_EP          USB_EP2
#define USB_INTRIN_EP           USB_EP3
#define USB_INTROUT_EP          USB_EP4
#define USB_ISOCIN_EP           USB_EP5
#define USB_ISOCOUT_EP          USB_EP6


/*
extern void     usb_test_InstallID(void) _SECTION(".kercfg_text");
extern UINT32   FLG_ID_USBTEST;
extern THREAD_HANDLE   USBOTEST_TSK_ID1;
extern THREAD_HANDLE   USBOTEST_TSK_ID2;
extern THREAD_HANDLE   USBOTEST_TSK_ID3;
extern THREAD_HANDLE   USBOTEST_TSK_ID4;
extern THREAD_HANDLE   USBOTEST_TSK_ID5;
extern THREAD_HANDLE   USBOTEST_TSK_IDV1;
extern THREAD_HANDLE   USBOTEST_TSK_IDV2;
*/


typedef enum {
	EMUUSBTEST_MODE_CIO_BIO_RIO_IIO,//Cx-IO,BULK-IO,INTR-IO,ISOC-IO
	EMUUSBTEST_MODE_CIO_BIO_RIO_II, //Cx-IO,BULK-IO,INTR-IO,ISOC-I
	EMUUSBTEST_MODE_CIO_BIO_RIO,    //Cx-IO,BULK-IO,INTR-IO
	EMUUSBTEST_MODE_UVC_2V_CIO_BIO,     //UVC Header 2V + Cx-IO + BULK-IO
	EMUUSBTEST_MODE_UVC_2V_CIO_BIO_II,  //UVC Header 2V + Cx-IO + BULK-IO + ISOC-I

	ENUM_DUMMY4WORD(EMUUSBTEST_MODE)
} EMUUSBTEST_MODE;







extern void emu_usb_test_open(EMUUSBTEST_MODE test_mode);
extern void emu_usb_test_close(void);


#endif

