#
# Xmedia Clock specific Makefile
#

obj-y	+= clk.o
obj-$(CONFIG_COMMON_CLK_XM72050200)  += clk-xm72050200.o
obj-$(CONFIG_COMMON_CLK_XM72050300)  += clk-xm72050300.o
obj-$(CONFIG_COMMON_CLK_XM72020300)  += clk-xm72020300.o
obj-$(CONFIG_COMMON_CLK_XM76050100)  += clk-xm76050100.o
obj-$(CONFIG_COMMON_CLK_XM72050500)  += clk-xm72050500.o
obj-$(CONFIG_COMMON_CLK_XM720XXX)  += clk-xm720xxx.o
obj-$(CONFIG_RESET_XMEDIA)	+= reset.o
