#ifndef _DT_BINDINGS_DISPLAY_NVT_PIN_H
#define _DT_BINDINGS_DISPLAY_NVT_PIN_H

/**
    Pinmux selection for LCD

*/

#define PINMUX_LCD_SEL_GPIO 				0
#define PINMUX_LCD_SEL_CCIR656				1
#define PINMUX_LCD_SEL_CCIR656_16BITS 			2
#define PINMUX_LCD_SEL_CCIR601				3
#define PINMUX_LCD_SEL_CCIR601_16BITS			4
#define PINMUX_LCD_SEL_SERIAL_RGB_6BITS 		5
#define PINMUX_LCD_SEL_SERIAL_RGB_8BITS 		6
#define PINMUX_LCD_SEL_SERIAL_YCbCr_8BITS		7
#define PINMUX_LCD_SEL_PARALLE_RGB565			8
#define PINMUX_LCD_SEL_PARALLE_RGB666			9
#define PINMUX_LCD_SEL_PARALLE_RGB888			10
#define PINMUX_LCD_SEL_RGB_16BITS			11
#define PINMUX_LCD_SEL_PARALLE_MI_8BITS 		12
#define PINMUX_LCD_SEL_PARALLE_MI_9BITS 		13
#define PINMUX_LCD_SEL_PARALLE_MI_16BITS		14
#define PINMUX_LCD_SEL_PARALLE_MI_18BITS		15
#define PINMUX_LCD_SEL_SERIAL_MI_SDIO			16
#define PINMUX_LCD_SEL_SERIAL_MI_SDI_SDO		17
#define PINMUX_LCD_SEL_MIPI				18


#endif
