#ifndef __SENPHY_REG_H__
#define __SENPHY_REG_H__

#ifdef __KERNEL__
#include "mach/rcw_macro.h"
#include "kwrap/type.h"
#else

#include "rcw_macro.h"

#endif

#if 1
// 0x00 SENPHY Control Register 0
REGDEF_OFFSET(SENPHY_CTRL0_REG, 0x00)
REGDEF_BEGIN(SENPHY_CTRL0_REG)
REGDEF_BIT(, 4)
REGDEF_BIT(EN_BIAS, 1)
REGDEF_BIT(DLY_EN, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(IADJ, 2)
REGDEF_BIT(, 14)
REGDEF_BIT(PHY_CK_MODE, 1)
REGDEF_BIT(, 7)
REGDEF_END(SENPHY_CTRL0_REG)

// 0x0C SENPHY Control Register 2
REGDEF_OFFSET(SENPHY_CTRL2_REG, 0x0C)
REGDEF_BEGIN(SENPHY_CTRL2_REG)
REGDEF_BIT(CLKENO_DLY, 8)
REGDEF_BIT(, 8)
REGDEF_BIT(CSI_DDLY_LVDS, 4)
REGDEF_BIT(, 12)
REGDEF_END(SENPHY_CTRL2_REG)


// 0x10 SENPHY Control Register 3
REGDEF_OFFSET(SENPHY_CTRL3_REG, 0x10)
REGDEF_BEGIN(SENPHY_CTRL3_REG)
REGDEF_BIT(D01RST, 1)
REGDEF_BIT(D23RST, 1)
REGDEF_BIT(, 30)
REGDEF_END(SENPHY_CTRL3_REG)


// 0x18 SENPHY Control Register 4
REGDEF_OFFSET(SENPHY_CTRL4_REG, 0x18)
REGDEF_BEGIN(SENPHY_CTRL4_REG)
REGDEF_BIT(CK0_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK1_DESKEW, 3)
REGDEF_BIT(, 25)
REGDEF_END(SENPHY_CTRL4_REG)


// 0x20 SENPHY Control Register 5
REGDEF_OFFSET(SENPHY_CTRL5_REG, 0x20)
REGDEF_BEGIN(SENPHY_CTRL5_REG)
REGDEF_BIT(DL0_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL1_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL2_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL3_DESKEW, 3)
REGDEF_BIT(, 17)
REGDEF_END(SENPHY_CTRL5_REG)


// 0x28 SENPHY Control Register 6
REGDEF_OFFSET(SENPHY_CTRL6_REG, 0x28)
REGDEF_BEGIN(SENPHY_CTRL6_REG)
REGDEF_BIT(CLKO0_EDGE, 1)
REGDEF_BIT(CLKO1_EDGE, 1)
REGDEF_BIT(, 14)
REGDEF_BIT(DL0_INV, 1)
REGDEF_BIT(DL1_INV, 1)
REGDEF_BIT(DL2_INV, 1)
REGDEF_BIT(DL3_INV, 1)
REGDEF_BIT(, 12)
REGDEF_END(SENPHY_CTRL6_REG)

// 0x28 SENPHY Control Register 6
REGDEF_OFFSET(SENPHY_MODE_REG, 0x2C)
REGDEF_BEGIN(SENPHY_MODE_REG)
REGDEF_BIT(CSI_MODE, 1)
REGDEF_BIT(LVDS_MODE, 1)
REGDEF_BIT(CSI2_MODE, 1)
REGDEF_BIT(LVDS2_MODE, 1)
REGDEF_BIT(, 28)
REGDEF_END(SENPHY_MODE_REG)


#else
// 0x00 SENPHY Control Register 0
REGDEF_OFFSET(SENPHY_CTRL0_REG, 0x00)
REGDEF_BEGIN(SENPHY_CTRL0_REG)
REGDEF_BIT(, 4)
REGDEF_BIT(EN_BIAS, 1)
REGDEF_BIT(DLY_EN, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(IADJ, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CURR_DIV2, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(HSRX_OPT, 2)
REGDEF_BIT(, 14)
REGDEF_END(SENPHY_CTRL0_REG)


// 0x08 SENPHY Control Register 1
REGDEF_OFFSET(SENPHY_CTRL1_REG, 0x08)
REGDEF_BEGIN(SENPHY_CTRL1_REG)
REGDEF_BIT(D0CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D1CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D2CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D3CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D4CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D5CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D6CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D7CKSRC, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_CTRL1_REG)


// 0x0C SENPHY Control Register 2
REGDEF_OFFSET(SENPHY_CTRL2_REG, 0x0C)
REGDEF_BEGIN(SENPHY_CTRL2_REG)
REGDEF_BIT(CLKENO_DLY, 8)
REGDEF_BIT(, 24)
REGDEF_END(SENPHY_CTRL2_REG)


// 0x10 SENPHY Control Register 3
REGDEF_OFFSET(SENPHY_CTRL3_REG, 0x10)
REGDEF_BEGIN(SENPHY_CTRL3_REG)
REGDEF_BIT(D0RST, 1)
REGDEF_BIT(D1RST, 1)
REGDEF_BIT(D2RST, 1)
REGDEF_BIT(D3RST, 1)
REGDEF_BIT(D4RST, 1)
REGDEF_BIT(D5RST, 1)
REGDEF_BIT(D6RST, 1)
REGDEF_BIT(D7RST, 1)
REGDEF_BIT(, 24)
REGDEF_END(SENPHY_CTRL3_REG)


// 0x18 SENPHY Control Register 4
REGDEF_OFFSET(SENPHY_CTRL4_REG, 0x18)
REGDEF_BEGIN(SENPHY_CTRL4_REG)
REGDEF_BIT(CK0_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK1_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK2_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK3_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK4_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK5_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK6_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CK7_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_CTRL4_REG)


// 0x20 SENPHY Control Register 5
REGDEF_OFFSET(SENPHY_CTRL5_REG, 0x20)
REGDEF_BEGIN(SENPHY_CTRL5_REG)
REGDEF_BIT(DL0_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL1_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL2_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL3_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL4_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL5_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL6_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DL7_DESKEW, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_CTRL5_REG)


// 0x28 SENPHY Control Register 6
REGDEF_OFFSET(SENPHY_CTRL6_REG, 0x28)
REGDEF_BEGIN(SENPHY_CTRL6_REG)
REGDEF_BIT(CLKO0_EDGE, 1)
REGDEF_BIT(CLKO1_EDGE, 1)
REGDEF_BIT(CLKO2_EDGE, 1)
REGDEF_BIT(CLKO3_EDGE, 1)
REGDEF_BIT(CLKO4_EDGE, 1)
REGDEF_BIT(CLKO5_EDGE, 1)
REGDEF_BIT(CLKO6_EDGE, 1)
REGDEF_BIT(CLKO7_EDGE, 1)
REGDEF_BIT(, 8)
REGDEF_BIT(DL0_INV, 1)
REGDEF_BIT(DL1_INV, 1)
REGDEF_BIT(DL2_INV, 1)
REGDEF_BIT(DL3_INV, 1)
REGDEF_BIT(DL4_INV, 1)
REGDEF_BIT(DL5_INV, 1)
REGDEF_BIT(DL6_INV, 1)
REGDEF_BIT(DL7_INV, 1)
REGDEF_BIT(, 8)
REGDEF_END(SENPHY_CTRL6_REG)
#endif


#endif
