
obj-$(CONFIG_ARCH_GK710XS) += gk710xs.o
obj-$(CONFIG_ARCH_GK710XS) += irq.o
obj-$(CONFIG_ARCH_GK710XS) += rct.o
obj-$(CONFIG_ARCH_GK710XS) += mdma.o dma.o
obj-$(CONFIG_ARCH_GK710XS) += vi.o
obj-$(CONFIG_ARCH_GK710XS) += mach-gk710xs.o

ccflags-$(CONFIG_ARCH_GK710XS) += -D__LINUX__ 

ccflags-$(CONFIG_ARCH_GK710XS) += -Iarch/arm/mach-gk710xs/include

