
#include "pinctrl.h"
#include "pinctrl_osdep.h"
#include "board_config.h"

PINCTRL_FUNC(CIS_HSYNC, 0, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO20, 0, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_VSYNC, 1, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO21, 1, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM0, 1, FUNC2, PUPD_UP);
PINCTRL_FUNC(UART1_TX, 1, FUNC3, PUPD_UP);
PINCTRL_FUNC(CIS_PCLK, 2, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO19, 2, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM1, 2, FUNC2, PUPD_UP);
PINCTRL_FUNC(UART1_RX, 2, FUNC3, PUPD_UP);
PINCTRL_FUNC(CIS_D_0, 3, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO22, 3, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM2, 3, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(USB_PWREN, 3, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(AD_I2S_DI, 3, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(RTC_CLK, 3, FUNC5, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_1, 4, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO23, 4, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM3, 4, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(AC_MCLK, 4, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(AD_I2S_CLK, 4, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_2, 5, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO24, 5, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM4, 5, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(I2S_DI, 5, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(AD_I2S_WS, 5, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_3, 6, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO25, 6, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM5, 6, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(I2S_CLK, 6, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(DA_I2S_DO, 6, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_4, 7, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO26, 7, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM6, 7, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(I2S_WS, 7, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(DA_I2S_WS, 7, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_5, 8, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO27, 8, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(PWM7, 8, FUNC2, PUPD_DOWN);
PINCTRL_FUNC(I2S_DO, 8, FUNC3, PUPD_DOWN);
PINCTRL_FUNC(DA_I2S_CLK, 8, FUNC4, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_6, 9, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO28, 9, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_7, 10, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO29, 10, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_8, 11, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO30, 11, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_9, 12, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO31, 12, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_10, 13, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO32, 13, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(CIS_D_11, 14, FUNC0, PUPD_DOWN);
PINCTRL_FUNC(GPIO33, 14, FUNC1, PUPD_DOWN);
PINCTRL_FUNC(MAC_RMII_CLK, 15, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO15, 15, FUNC1, PUPD_UP);
PINCTRL_FUNC(SD1_CLK, 15, FUNC2, PUPD_UP);
PINCTRL_FUNC(PWM0, 15, FUNC3, PUPD_UP);
PINCTRL_FUNC(USB_PWREN, 15, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_DI, 15, FUNC5, PUPD_UP);
PINCTRL_FUNC(MAC_REF_CLK, 16, FUNC0, PUPD_NONE);
PINCTRL_FUNC(MAC_MDC, 17, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO34, 17, FUNC1, PUPD_UP);
PINCTRL_FUNC(SD1_WP, 17, FUNC2, PUPD_UP);
PINCTRL_FUNC(I2C1_SDA, 17, FUNC3, PUPD_UP);
PINCTRL_FUNC(UART1_TX, 17, FUNC4, PUPD_UP);
PINCTRL_FUNC(SSI1_CLK, 17, FUNC5, PUPD_UP);
PINCTRL_FUNC(MAC_MDIO, 18, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO17, 18, FUNC1, PUPD_NONE);
PINCTRL_FUNC(ARM_JTAG_TDO, 18, FUNC2, PUPD_NONE);
PINCTRL_FUNC(I2C1_SCL, 18, FUNC3, PUPD_NONE);
PINCTRL_FUNC(UART1_RX, 18, FUNC4, PUPD_NONE);
PINCTRL_FUNC(PWM7, 18, FUNC5, PUPD_NONE);
PINCTRL_FUNC(PWM0, 19, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO35, 19, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM1, 20, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO36, 20, FUNC1, PUPD_UP);
PINCTRL_FUNC(MAC_RXCK, 21, FUNC0, PUPD_NONE);
PINCTRL_FUNC(MAC_RXD_0, 22, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO16, 22, FUNC1, PUPD_UP);
PINCTRL_FUNC(SD1_DATA_0, 22, FUNC2, PUPD_UP);
PINCTRL_FUNC(PWM1, 22, FUNC3, PUPD_UP);
PINCTRL_FUNC(AD_I2S_DI, 22, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_CLK, 22, FUNC5, PUPD_UP);
PINCTRL_FUNC(MAC_RXD_1, 23, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO38, 23, FUNC1, PUPD_UP);
PINCTRL_FUNC(SD1_DATA_1, 23, FUNC2, PUPD_UP);
PINCTRL_FUNC(PWM2, 23, FUNC3, PUPD_UP);
PINCTRL_FUNC(AD_I2S_CLK, 23, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_WS, 23, FUNC5, PUPD_UP);
PINCTRL_FUNC(PWM2, 24, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO39, 24, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM3, 25, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO40, 25, FUNC1, PUPD_UP);
PINCTRL_FUNC(MAC_RXDV, 26, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO41, 26, FUNC1, PUPD_UP);
PINCTRL_FUNC(SD1_CD, 26, FUNC2, PUPD_UP);
PINCTRL_FUNC(PWM3, 26, FUNC3, PUPD_UP);
PINCTRL_FUNC(AD_I2S_WS, 26, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_DO, 26, FUNC5, PUPD_UP);
PINCTRL_FUNC(MAC_TXCK, 27, FUNC0, PUPD_NONE);
PINCTRL_FUNC(MAC_TXD_0, 28, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO42, 28, FUNC1, PUPD_NONE);
PINCTRL_FUNC(SD1_DATA_2, 28, FUNC2, PUPD_NONE);
PINCTRL_FUNC(PWM4, 28, FUNC3, PUPD_NONE);
PINCTRL_FUNC(DA_I2S_DO, 28, FUNC4, PUPD_NONE);
PINCTRL_FUNC(SSI1_TXD, 28, FUNC5, PUPD_NONE);
PINCTRL_FUNC(MAC_TXD_1, 29, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO43, 29, FUNC1, PUPD_NONE);
PINCTRL_FUNC(SD1_DATA_3, 29, FUNC2, PUPD_NONE);
PINCTRL_FUNC(PWM5, 29, FUNC3, PUPD_NONE);
PINCTRL_FUNC(DA_I2S_WS, 29, FUNC4, PUPD_NONE);
PINCTRL_FUNC(SSI1_RXD, 29, FUNC5, PUPD_NONE);
PINCTRL_FUNC(PWM4, 30, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO44, 30, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM5, 31, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO45, 31, FUNC1, PUPD_UP);
PINCTRL_FUNC(MAC_TXEN, 32, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO46, 32, FUNC1, PUPD_NONE);
PINCTRL_FUNC(SD1_CMD_RSP, 32, FUNC2, PUPD_NONE);
PINCTRL_FUNC(PWM6, 32, FUNC3, PUPD_NONE);
PINCTRL_FUNC(DA_I2S_CLK, 32, FUNC4, PUPD_NONE);
PINCTRL_FUNC(AC_MCLK, 32, FUNC5, PUPD_NONE);
PINCTRL_FUNC(PWM6, 33, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO47, 33, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM7, 34, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO37, 34, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TRSTN, 35, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO0, 35, FUNC1, PUPD_UP);
PINCTRL_FUNC(SSI1_TXD, 35, FUNC2, PUPD_UP);
PINCTRL_FUNC(SSI2_TXD, 35, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM0, 35, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_DI, 35, FUNC5, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TMS, 36, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO1, 36, FUNC1, PUPD_UP);
PINCTRL_FUNC(SSI1_RXD, 36, FUNC2, PUPD_UP);
PINCTRL_FUNC(SSI2_RXD, 36, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM1, 36, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_WS, 36, FUNC5, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TCK, 37, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO2, 37, FUNC1, PUPD_UP);
PINCTRL_FUNC(SSI1_CLK, 37, FUNC2, PUPD_UP);
PINCTRL_FUNC(SSI2_CLK, 37, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM2, 37, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_DO, 37, FUNC5, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TDI, 38, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO3, 38, FUNC1, PUPD_UP);
PINCTRL_FUNC(SSI1_CSN_0, 38, FUNC2, PUPD_UP);
PINCTRL_FUNC(SSI2_CSN, 38, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM3, 38, FUNC4, PUPD_UP);
PINCTRL_FUNC(I2S_CLK, 38, FUNC5, PUPD_UP);
PINCTRL_FUNC(GPIO4, 39, FUNC0, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TCK, 40, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO5, 40, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TRSTN, 41, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO6, 41, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TMS, 42, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO7, 42, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TDI, 43, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO8, 43, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARM_JTAG_TDO, 44, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO9, 44, FUNC1, PUPD_NONE);
PINCTRL_FUNC(UART1_TX, 45, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO10, 45, FUNC1, PUPD_UP);
PINCTRL_FUNC(UART1_RX, 46, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO11, 46, FUNC1, PUPD_UP);
PINCTRL_FUNC(PWM0, 47, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO12, 47, FUNC1, PUPD_NONE);
PINCTRL_FUNC(CIS_CLK, 47, FUNC2, PUPD_NONE);
PINCTRL_FUNC(PWM1, 48, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO13, 48, FUNC1, PUPD_NONE);
PINCTRL_FUNC(PWM2, 49, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO14, 49, FUNC1, PUPD_NONE);
PINCTRL_FUNC(UART0_RX, 50, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO48, 50, FUNC1, PUPD_UP);
PINCTRL_FUNC(I2S_WS, 50, FUNC2, PUPD_UP);
PINCTRL_FUNC(UART0_TX, 51, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO49, 51, FUNC1, PUPD_UP);
PINCTRL_FUNC(I2S_CLK, 51, FUNC2, PUPD_UP);
PINCTRL_FUNC(I2C0_SCL, 52, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO57, 52, FUNC1, PUPD_NONE);
PINCTRL_FUNC(I2C0_SDA, 53, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO56, 53, FUNC1, PUPD_NONE);
PINCTRL_FUNC(I2C1_SCL, 54, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO51, 54, FUNC1, PUPD_NONE);
PINCTRL_FUNC(I2S_DI, 54, FUNC2, PUPD_NONE);
PINCTRL_FUNC(I2C1_SDA, 55, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO50, 55, FUNC1, PUPD_NONE);
PINCTRL_FUNC(I2S_DO, 55, FUNC2, PUPD_NONE);
PINCTRL_FUNC(SSI0_CLK, 56, FUNC0, PUPD_NONE);
PINCTRL_FUNC(SSI0_TXD, 57, FUNC0, PUPD_NONE);
PINCTRL_FUNC(SSI0_CSN_0, 58, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO54, 58, FUNC1, PUPD_UP);
PINCTRL_FUNC(SSI0_CSN_1, 59, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO55, 59, FUNC1, PUPD_UP);
PINCTRL_FUNC(USB_PWREN, 59, FUNC2, PUPD_UP);
PINCTRL_FUNC(AC_MCLK, 59, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM3, 59, FUNC4, PUPD_UP);
PINCTRL_FUNC(UART1_TX, 59, FUNC5, PUPD_UP);
PINCTRL_FUNC(SSI0_RXD, 60, FUNC0, PUPD_UP);
PINCTRL_FUNC(SD0_CD, 61, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO52, 61, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARC_JTAG_TRSTN, 61, FUNC2, PUPD_UP);
PINCTRL_FUNC(PAE_JTAG_TRSTN, 61, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM5, 61, FUNC4, PUPD_UP);
PINCTRL_FUNC(SSI2_TXD, 61, FUNC5, PUPD_UP);
PINCTRL_FUNC(SD0_WP, 62, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO53, 62, FUNC1, PUPD_UP);
PINCTRL_FUNC(USB_PWREN, 62, FUNC2, PUPD_UP);
PINCTRL_FUNC(SD0_CLK, 63, FUNC0, PUPD_NONE);
PINCTRL_FUNC(GPIO63, 63, FUNC1, PUPD_NONE);
PINCTRL_FUNC(ARC_JTAG_TMS, 63, FUNC2, PUPD_NONE);
PINCTRL_FUNC(PAE_JTAG_TMS, 63, FUNC3, PUPD_NONE);
PINCTRL_FUNC(PWM6, 63, FUNC4, PUPD_NONE);
PINCTRL_FUNC(SSI2_RXD, 63, FUNC5, PUPD_NONE);
PINCTRL_FUNC(SD0_CMD_RSP, 64, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO11, 64, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARC_JTAG_TCK, 64, FUNC2, PUPD_UP);
PINCTRL_FUNC(PAE_JTAG_TCK, 64, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM7, 64, FUNC4, PUPD_UP);
PINCTRL_FUNC(SSI2_CLK, 64, FUNC5, PUPD_UP);
PINCTRL_FUNC(SD0_DATA_0, 65, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO62, 65, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARC_JTAG_TDI, 65, FUNC2, PUPD_UP);
PINCTRL_FUNC(PAE_JTAG_TDI, 65, FUNC3, PUPD_UP);
PINCTRL_FUNC(PWM4, 65, FUNC4, PUPD_UP);
PINCTRL_FUNC(SSI2_CSN, 65, FUNC5, PUPD_UP);
PINCTRL_FUNC(SD0_DATA_1, 66, FUNC0, PUPD_UP);
PINCTRL_FUNC(GPIO61, 66, FUNC1, PUPD_UP);
PINCTRL_FUNC(ARC_JTAG_TDO, 66, FUNC2, PUPD_UP);
PINCTRL_FUNC(PAE_JTAG_TDO, 66, FUNC3, PUPD_UP);
PINCTRL_FUNC(SD0_WP, 66, FUNC4, PUPD_UP);
PINCTRL_FUNC(UART1_TX, 66, FUNC5, PUPD_UP);

PINCTRL_MUX(USB_PWREN, 0, &PAD3_USB_PWREN, &PAD15_USB_PWREN,
		&PAD59_USB_PWREN, &PAD62_USB_PWREN);
PINCTRL_MUX(AC_MCLK, 2, &PAD4_AC_MCLK, &PAD32_AC_MCLK, &PAD59_AC_MCLK);

PINCTRL_MUX(ACI2S_AD_CLK, 1, &PAD4_AD_I2S_CLK, &PAD23_AD_I2S_CLK);
PINCTRL_MUX(ACI2S_AD_DI, 1, &PAD3_AD_I2S_DI, &PAD22_AD_I2S_DI);
PINCTRL_MUX(ACI2S_AD_WS, 0, &PAD5_AD_I2S_WS, &PAD26_AD_I2S_WS);
PINCTRL_MUX(ACI2S_DA_CLK, 0, &PAD8_DA_I2S_CLK, &PAD32_DA_I2S_CLK);
PINCTRL_MUX(ACI2S_DA_DO, 0, &PAD6_DA_I2S_DO, &PAD28_DA_I2S_DO);
PINCTRL_MUX(ACI2S_DA_WS, 0, &PAD7_DA_I2S_WS, &PAD29_DA_I2S_WS);

PINCTRL_MUX(DWI2S_CLK, 0, &PAD6_I2S_CLK, &PAD22_I2S_CLK,
		&PAD38_I2S_CLK, &PAD51_I2S_CLK);
PINCTRL_MUX(DWI2S_DI, 0, &PAD5_I2S_DI, &PAD15_I2S_DI,
		&PAD35_I2S_DI, &PAD54_I2S_DI);
PINCTRL_MUX(DWI2S_DO, 0, &PAD8_I2S_DO, &PAD26_I2S_DO,
		&PAD37_I2S_DO, &PAD55_I2S_DO);
PINCTRL_MUX(DWI2S_WS, 0, &PAD7_I2S_WS, &PAD23_I2S_WS,
		&PAD36_I2S_WS, &PAD50_I2S_WS);

PINCTRL_MUX(ARCJTAG_TCK, 0, &PAD64_ARC_JTAG_TCK);
PINCTRL_MUX(ARCJTAG_TDI, 0, &PAD65_ARC_JTAG_TDI);
PINCTRL_MUX(ARCJTAG_TDO, 0, &PAD66_ARC_JTAG_TDO);
PINCTRL_MUX(ARCJTAG_TMS, 0, &PAD63_ARC_JTAG_TMS);
PINCTRL_MUX(ARCJTAG_TRSTN, 0, &PAD61_ARC_JTAG_TRSTN);

PINCTRL_MUX(ARMJTAG_TCK, 1, &PAD37_ARM_JTAG_TCK, &PAD40_ARM_JTAG_TCK);
PINCTRL_MUX(ARMJTAG_TDI, 1, &PAD38_ARM_JTAG_TDI, &PAD43_ARM_JTAG_TDI);
PINCTRL_MUX(ARMJTAG_TDO, 1, &PAD18_ARM_JTAG_TDO, &PAD44_ARM_JTAG_TDO);
PINCTRL_MUX(ARMJTAG_TMS, 1, &PAD36_ARM_JTAG_TMS, &PAD42_ARM_JTAG_TMS);
PINCTRL_MUX(ARMJTAG_TRSTN, 1, &PAD35_ARM_JTAG_TRSTN, &PAD41_ARM_JTAG_TRSTN);

PINCTRL_MUX(PAEJTAG_TCK, 0, &PAD64_PAE_JTAG_TCK);
PINCTRL_MUX(PAEJTAG_TDI, 0, &PAD65_PAE_JTAG_TDI);
PINCTRL_MUX(PAEJTAG_TDO, 0, &PAD66_PAE_JTAG_TDO);
PINCTRL_MUX(PAEJTAG_TMS, 0, &PAD63_PAE_JTAG_TMS);
PINCTRL_MUX(PAEJTAG_TRSTN, 0, &PAD61_PAE_JTAG_TRSTN);

PINCTRL_MUX(CIS_CLK, 0, &PAD47_CIS_CLK);
PINCTRL_MUX(CIS_PCLK, 0, &PAD2_CIS_PCLK);
PINCTRL_MUX(CIS_HSYNC, 0, &PAD0_CIS_HSYNC);
PINCTRL_MUX(CIS_VSYNC, 0, &PAD1_CIS_VSYNC);
PINCTRL_MUX(CIS_D_0, 0, &PAD3_CIS_D_0);
PINCTRL_MUX(CIS_D_1, 0, &PAD4_CIS_D_1);
PINCTRL_MUX(CIS_D_2, 0, &PAD5_CIS_D_2);
PINCTRL_MUX(CIS_D_3, 0, &PAD6_CIS_D_3);
PINCTRL_MUX(CIS_D_4, 0, &PAD7_CIS_D_4);
PINCTRL_MUX(CIS_D_5, 0, &PAD8_CIS_D_5);
PINCTRL_MUX(CIS_D_6, 0, &PAD9_CIS_D_6);
PINCTRL_MUX(CIS_D_7, 0, &PAD10_CIS_D_7);
PINCTRL_MUX(CIS_D_8, 0, &PAD11_CIS_D_8);
PINCTRL_MUX(CIS_D_9, 0, &PAD12_CIS_D_9);
PINCTRL_MUX(CIS_D_10, 0, &PAD13_CIS_D_10);
PINCTRL_MUX(CIS_D_11, 0, &PAD14_CIS_D_11);

PINCTRL_MUX(I2C0_SCL, 0, &PAD52_I2C0_SCL);
PINCTRL_MUX(I2C0_SDA, 0, &PAD53_I2C0_SDA);

PINCTRL_MUX(I2C1_SCL, 1, &PAD18_I2C1_SCL, &PAD54_I2C1_SCL);
PINCTRL_MUX(I2C1_SDA, 1, &PAD17_I2C1_SDA, &PAD55_I2C1_SDA);

PINCTRL_MUX(MAC_REF_CLK, 0, &PAD16_MAC_REF_CLK);
PINCTRL_MUX(MAC_RMII_CLK, 0, &PAD15_MAC_RMII_CLK);
PINCTRL_MUX(MAC_MDC, 0, &PAD17_MAC_MDC);
PINCTRL_MUX(MAC_MDIO, 0, &PAD18_MAC_MDIO);
PINCTRL_MUX(MAC_RXCK, 0, &PAD21_MAC_RXCK);
PINCTRL_MUX(MAC_RXD_0, 0, &PAD22_MAC_RXD_0);
PINCTRL_MUX(MAC_RXD_1, 0, &PAD23_MAC_RXD_1);
PINCTRL_MUX(MAC_RXDV, 0, &PAD26_MAC_RXDV);
PINCTRL_MUX(MAC_TXCK, 0, &PAD27_MAC_TXCK);
PINCTRL_MUX(MAC_TXD_0, 0, &PAD28_MAC_TXD_0);
PINCTRL_MUX(MAC_TXD_1, 0, &PAD29_MAC_TXD_1);
PINCTRL_MUX(MAC_TXEN, 0, &PAD32_MAC_TXEN);

PINCTRL_MUX(PWM0, 3, &PAD1_PWM0, &PAD15_PWM0,
		&PAD19_PWM0, &PAD35_PWM0, &PAD47_PWM0);
PINCTRL_MUX(PWM1, 3, &PAD2_PWM1, &PAD20_PWM1,
		&PAD22_PWM1, &PAD36_PWM1, &PAD48_PWM1);
PINCTRL_MUX(PWM2, 3, &PAD3_PWM2, &PAD23_PWM2,
		&PAD24_PWM2, &PAD37_PWM2, &PAD49_PWM2);
PINCTRL_MUX(PWM3, 3, &PAD4_PWM3, &PAD25_PWM3,
		&PAD26_PWM3, &PAD38_PWM3, &PAD59_PWM3);
PINCTRL_MUX(PWM4, 2, &PAD5_PWM4, &PAD28_PWM4, &PAD30_PWM4,
		&PAD65_PWM4);
PINCTRL_MUX(PWM5, 2, &PAD6_PWM5, &PAD29_PWM5, &PAD31_PWM5,
		&PAD61_PWM5);
PINCTRL_MUX(PWM6, 2, &PAD7_PWM6, &PAD32_PWM6, &PAD33_PWM6,
		&PAD63_PWM6);
PINCTRL_MUX(PWM7, 2, &PAD8_PWM7, &PAD18_PWM7, &PAD34_PWM7,
		&PAD64_PWM7);

PINCTRL_MUX(SD0_CLK, 0, &PAD63_SD0_CLK);
PINCTRL_MUX(SD0_CD, 0, &PAD61_SD0_CD);
PINCTRL_MUX(SD0_CMD_RSP, 0, &PAD64_SD0_CMD_RSP);
PINCTRL_MUX(SD0_WP, 0, &PAD62_SD0_WP, &PAD66_SD0_WP);
PINCTRL_MUX(SD0_DATA_0, 0, &PAD65_SD0_DATA_0);
PINCTRL_MUX(SD0_DATA_1, 0, &PAD66_SD0_DATA_1);

PINCTRL_MUX(SD1_CLK, 0, &PAD15_SD1_CLK);
PINCTRL_MUX(SD1_CD, 0, &PAD26_SD1_CD);
PINCTRL_MUX(SD1_CMD_RSP, 0, &PAD32_SD1_CMD_RSP);
PINCTRL_MUX(SD1_WP, 0, &PAD17_SD1_WP);
PINCTRL_MUX(SD1_DATA_0, 0, &PAD22_SD1_DATA_0);
PINCTRL_MUX(SD1_DATA_1, 0, &PAD23_SD1_DATA_1);
PINCTRL_MUX(SD1_DATA_2, 0, &PAD28_SD1_DATA_2);
PINCTRL_MUX(SD1_DATA_3, 0, &PAD29_SD1_DATA_3);

PINCTRL_MUX(SSI0_CLK, 0, &PAD56_SSI0_CLK);
PINCTRL_MUX(SSI0_RXD, 0, &PAD60_SSI0_RXD);
PINCTRL_MUX(SSI0_TXD, 0, &PAD57_SSI0_TXD);
PINCTRL_MUX(SSI0_CSN_0, 0, &PAD58_SSI0_CSN_0);
PINCTRL_MUX(SSI0_CSN_1, 0, &PAD59_SSI0_CSN_1);

PINCTRL_MUX(SSI1_CLK, 0, &PAD37_SSI1_CLK);
PINCTRL_MUX(SSI1_RXD, 1, &PAD29_SSI1_RXD, &PAD36_SSI1_RXD);
PINCTRL_MUX(SSI1_TXD, 1, &PAD28_SSI1_TXD, &PAD35_SSI1_TXD);
PINCTRL_MUX(SSI1_CSN_0, 0, &PAD38_SSI1_CSN_0);

PINCTRL_MUX(SSI2_CLK, 0, &PAD37_SSI2_CLK, &PAD64_SSI2_CLK);
PINCTRL_MUX(SSI2_RXD, 0, &PAD36_SSI2_RXD, &PAD63_SSI2_RXD);
PINCTRL_MUX(SSI2_TXD, 0, &PAD35_SSI2_TXD, &PAD61_SSI2_TXD);
PINCTRL_MUX(SSI2_CSN, 0, &PAD38_SSI2_CSN, &PAD65_SSI2_CSN);

PINCTRL_MUX(UART0_RX, 0, &PAD50_UART0_RX);
PINCTRL_MUX(UART0_TX, 0, &PAD51_UART0_TX);
PINCTRL_MUX(UART1_RX, 0, &PAD2_UART1_RX, &PAD18_UART1_RX,
		&PAD46_UART1_RX);
PINCTRL_MUX(UART1_TX, 0, &PAD1_UART1_TX, &PAD17_UART1_TX,
		&PAD45_UART1_TX, &PAD59_UART1_TX, &PAD66_UART1_TX);

PINCTRL_MUX(GPIO0, 0, &PAD35_GPIO0);
PINCTRL_MUX(GPIO1, 0, &PAD36_GPIO1);
PINCTRL_MUX(GPIO2, 0, &PAD37_GPIO2);
PINCTRL_MUX(GPIO3, 0, &PAD38_GPIO3);
PINCTRL_MUX(GPIO4, 0, &PAD39_GPIO4);
PINCTRL_MUX(GPIO5, 0, &PAD40_GPIO5);
PINCTRL_MUX(GPIO6, 0, &PAD41_GPIO6);
PINCTRL_MUX(GPIO7, 0, &PAD42_GPIO7);
PINCTRL_MUX(GPIO8, 0, &PAD43_GPIO8);
PINCTRL_MUX(GPIO9, 0, &PAD44_GPIO9);
PINCTRL_MUX(GPIO10, 0, &PAD45_GPIO10);
PINCTRL_MUX(GPIO11, 0, &PAD46_GPIO11, &PAD64_GPIO11);
PINCTRL_MUX(GPIO12, 0, &PAD47_GPIO12);
PINCTRL_MUX(GPIO13, 0, &PAD48_GPIO13);
PINCTRL_MUX(GPIO14, 0, &PAD49_GPIO14);
PINCTRL_MUX(GPIO15, 0, &PAD15_GPIO15);
PINCTRL_MUX(GPIO16, 0, &PAD22_GPIO16);
PINCTRL_MUX(GPIO17, 0, &PAD18_GPIO17);
PINCTRL_MUX(GPIO19, 0, &PAD2_GPIO19);
PINCTRL_MUX(GPIO20, 0, &PAD0_GPIO20);
PINCTRL_MUX(GPIO21, 0, &PAD1_GPIO21);
PINCTRL_MUX(GPIO22, 0, &PAD3_GPIO22);
PINCTRL_MUX(GPIO23, 0, &PAD4_GPIO23);
PINCTRL_MUX(GPIO24, 0, &PAD5_GPIO24);
PINCTRL_MUX(GPIO25, 0, &PAD6_GPIO25);
PINCTRL_MUX(GPIO26, 0, &PAD7_GPIO26);
PINCTRL_MUX(GPIO27, 0, &PAD8_GPIO27);
PINCTRL_MUX(GPIO28, 0, &PAD9_GPIO28);
PINCTRL_MUX(GPIO29, 0, &PAD10_GPIO29);
PINCTRL_MUX(GPIO30, 0, &PAD11_GPIO30);
PINCTRL_MUX(GPIO31, 0, &PAD12_GPIO31);
PINCTRL_MUX(GPIO32, 0, &PAD13_GPIO32);
PINCTRL_MUX(GPIO33, 0, &PAD14_GPIO33);
PINCTRL_MUX(GPIO34, 0, &PAD17_GPIO34);
PINCTRL_MUX(GPIO35, 0, &PAD19_GPIO35);
PINCTRL_MUX(GPIO36, 0, &PAD20_GPIO36);
PINCTRL_MUX(GPIO37, 0, &PAD34_GPIO37);
PINCTRL_MUX(GPIO38, 0, &PAD23_GPIO38);
PINCTRL_MUX(GPIO39, 0, &PAD24_GPIO39);
PINCTRL_MUX(GPIO40, 0, &PAD25_GPIO40);
PINCTRL_MUX(GPIO41, 0, &PAD26_GPIO41);
PINCTRL_MUX(GPIO42, 0, &PAD28_GPIO42);
PINCTRL_MUX(GPIO43, 0, &PAD29_GPIO43);
PINCTRL_MUX(GPIO44, 0, &PAD30_GPIO44);
PINCTRL_MUX(GPIO45, 0, &PAD31_GPIO45);
PINCTRL_MUX(GPIO46, 0, &PAD32_GPIO46);
PINCTRL_MUX(GPIO47, 0, &PAD33_GPIO47);
PINCTRL_MUX(GPIO48, 0, &PAD50_GPIO48);
PINCTRL_MUX(GPIO49, 0, &PAD51_GPIO49);
PINCTRL_MUX(GPIO50, 0, &PAD55_GPIO50);
PINCTRL_MUX(GPIO51, 0, &PAD54_GPIO51);
PINCTRL_MUX(GPIO52, 0, &PAD61_GPIO52);
PINCTRL_MUX(GPIO53, 0, &PAD62_GPIO53);
PINCTRL_MUX(GPIO54, 0, &PAD58_GPIO54);
PINCTRL_MUX(GPIO55, 0, &PAD59_GPIO55);
PINCTRL_MUX(GPIO56, 0, &PAD53_GPIO56);
PINCTRL_MUX(GPIO57, 0, &PAD52_GPIO57);
PINCTRL_MUX(GPIO61, 0, &PAD66_GPIO61);
PINCTRL_MUX(GPIO62, 0, &PAD65_GPIO62);
PINCTRL_MUX(GPIO63, 0, &PAD63_GPIO63);

PINCTRL_DEVICE(USB, 1, &MUX_USB_PWREN);
PINCTRL_DEVICE(AC, 1, &MUX_AC_MCLK);
PINCTRL_DEVICE(ACI2S, 6, &MUX_ACI2S_AD_CLK, &MUX_ACI2S_AD_DI, &MUX_ACI2S_AD_WS,
		&MUX_ACI2S_DA_CLK, &MUX_ACI2S_DA_DO, &MUX_ACI2S_DA_WS);
PINCTRL_DEVICE(DWI2S, 4, &MUX_DWI2S_CLK, &MUX_DWI2S_DI,
		&MUX_DWI2S_DO, &MUX_DWI2S_WS);
PINCTRL_DEVICE(ARCJTAG, 5, &MUX_ARCJTAG_TCK, &MUX_ARCJTAG_TDI, &MUX_ARCJTAG_TDO,
		&MUX_ARCJTAG_TMS, &MUX_ARCJTAG_TRSTN);
PINCTRL_DEVICE(ARMJTAG, 5, &MUX_ARMJTAG_TCK, &MUX_ARMJTAG_TDI, &MUX_ARMJTAG_TDO,
		&MUX_ARMJTAG_TMS, &MUX_ARMJTAG_TRSTN);
PINCTRL_DEVICE(PAEJTAG, 5, &MUX_PAEJTAG_TCK, &MUX_PAEJTAG_TDI, &MUX_PAEJTAG_TDO,
		&MUX_PAEJTAG_TMS, &MUX_PAEJTAG_TRSTN);
PINCTRL_DEVICE(CIS, 16, &MUX_CIS_CLK, &MUX_CIS_PCLK, &MUX_CIS_HSYNC,
		&MUX_CIS_VSYNC, &MUX_CIS_D_0, &MUX_CIS_D_1, &MUX_CIS_D_2,
		&MUX_CIS_D_3, &MUX_CIS_D_4, &MUX_CIS_D_5, &MUX_CIS_D_6,
		&MUX_CIS_D_7, &MUX_CIS_D_8, &MUX_CIS_D_9, &MUX_CIS_D_10,
		&MUX_CIS_D_11);
PINCTRL_DEVICE(CIS_10BIT, 14, &MUX_CIS_CLK, &MUX_CIS_PCLK, &MUX_CIS_HSYNC,
		&MUX_CIS_VSYNC, &MUX_CIS_D_2, &MUX_CIS_D_3,
		&MUX_CIS_D_4, &MUX_CIS_D_5, &MUX_CIS_D_6, &MUX_CIS_D_7,
		&MUX_CIS_D_8, &MUX_CIS_D_9, &MUX_CIS_D_10, &MUX_CIS_D_11);
PINCTRL_DEVICE(MIPI, 1, &MUX_CIS_CLK);
PINCTRL_DEVICE(I2C0, 2, &MUX_I2C0_SCL, &MUX_I2C0_SDA);
PINCTRL_DEVICE(I2C1, 2, &MUX_I2C1_SCL, &MUX_I2C1_SDA);
PINCTRL_DEVICE(RMII, 12, &MUX_MAC_REF_CLK, &MUX_MAC_RMII_CLK,
		&MUX_MAC_MDC, &MUX_MAC_MDIO, &MUX_MAC_RXD_0,
		&MUX_MAC_RXD_1, &MUX_MAC_RXDV, &MUX_MAC_TXD_0,
		&MUX_MAC_TXD_1, &MUX_MAC_TXEN, &MUX_MAC_TXCK, &MUX_MAC_RXCK);
PINCTRL_DEVICE(PWM0, 1, &MUX_PWM0);
PINCTRL_DEVICE(PWM1, 1, &MUX_PWM1);
PINCTRL_DEVICE(PWM2, 1, &MUX_PWM2);
PINCTRL_DEVICE(PWM3, 1, &MUX_PWM3);
PINCTRL_DEVICE(PWM4, 1, &MUX_PWM4);
PINCTRL_DEVICE(PWM5, 1, &MUX_PWM5);
PINCTRL_DEVICE(PWM6, 1, &MUX_PWM6);
PINCTRL_DEVICE(PWM7, 1, &MUX_PWM7);
PINCTRL_DEVICE(SD0, 6, &MUX_SD0_CLK, &MUX_SD0_CD, &MUX_SD0_CMD_RSP,
		&MUX_SD0_WP, &MUX_SD0_DATA_0, &MUX_SD0_DATA_1);
PINCTRL_DEVICE(SD0_CARD_1BIT, 5, &MUX_SD0_CLK, &MUX_SD0_CD, &MUX_SD0_CMD_RSP,
		&MUX_SD0_WP, &MUX_SD0_DATA_0);
PINCTRL_DEVICE(SD0_WIFI_2BIT, 4, &MUX_SD0_CLK, &MUX_SD0_CMD_RSP,
		&MUX_SD0_DATA_0, &MUX_SD0_DATA_1);
PINCTRL_DEVICE(SD1, 8, &MUX_SD1_CLK, &MUX_SD1_CD, &MUX_SD1_CMD_RSP,
		&MUX_SD1_WP, &MUX_SD1_DATA_0, &MUX_SD1_DATA_1, &MUX_SD1_DATA_2,
		&MUX_SD1_DATA_3);
PINCTRL_DEVICE(SSI0, 4, &MUX_SSI0_CLK, &MUX_SSI0_RXD, &MUX_SSI0_TXD,
		&MUX_GPIO54);
PINCTRL_DEVICE(SSI1, 4, &MUX_SSI1_CLK, &MUX_SSI1_RXD, &MUX_SSI1_TXD,
		&MUX_SSI1_CSN_0);
PINCTRL_DEVICE(SSI2, 4, &MUX_SSI2_CLK, &MUX_SSI2_RXD, &MUX_SSI2_TXD,
		&MUX_SSI2_CSN);
PINCTRL_DEVICE(UART0, 2, &MUX_UART0_RX, &MUX_UART0_TX);
PINCTRL_DEVICE(UART1, 2, &MUX_UART1_RX, &MUX_UART1_TX);
PINCTRL_DEVICE(GPIO0, 1, &MUX_GPIO0);
PINCTRL_DEVICE(GPIO1, 1, &MUX_GPIO1);
PINCTRL_DEVICE(GPIO2, 1, &MUX_GPIO2);
PINCTRL_DEVICE(GPIO3, 1, &MUX_GPIO3);
PINCTRL_DEVICE(GPIO4, 1, &MUX_GPIO4);
PINCTRL_DEVICE(GPIO5, 1, &MUX_GPIO5);
PINCTRL_DEVICE(GPIO6, 1, &MUX_GPIO6);
PINCTRL_DEVICE(GPIO7, 1, &MUX_GPIO7);
PINCTRL_DEVICE(GPIO8, 1, &MUX_GPIO8);
PINCTRL_DEVICE(GPIO9, 1, &MUX_GPIO9);
PINCTRL_DEVICE(GPIO10, 1, &MUX_GPIO10);
PINCTRL_DEVICE(GPIO11, 1, &MUX_GPIO11);
PINCTRL_DEVICE(GPIO12, 1, &MUX_GPIO12);
PINCTRL_DEVICE(GPIO13, 1, &MUX_GPIO13);
PINCTRL_DEVICE(GPIO14, 1, &MUX_GPIO14);
PINCTRL_DEVICE(GPIO15, 1, &MUX_GPIO15);
PINCTRL_DEVICE(GPIO16, 1, &MUX_GPIO16);
PINCTRL_DEVICE(GPIO17, 1, &MUX_GPIO17);
PINCTRL_DEVICE(GPIO19, 1, &MUX_GPIO19);
PINCTRL_DEVICE(GPIO20, 1, &MUX_GPIO20);
PINCTRL_DEVICE(GPIO21, 1, &MUX_GPIO21);
PINCTRL_DEVICE(GPIO22, 1, &MUX_GPIO22);
PINCTRL_DEVICE(GPIO23, 1, &MUX_GPIO23);
PINCTRL_DEVICE(GPIO24, 1, &MUX_GPIO24);
PINCTRL_DEVICE(GPIO25, 1, &MUX_GPIO25);
PINCTRL_DEVICE(GPIO26, 1, &MUX_GPIO26);
PINCTRL_DEVICE(GPIO27, 1, &MUX_GPIO27);
PINCTRL_DEVICE(GPIO28, 1, &MUX_GPIO28);
PINCTRL_DEVICE(GPIO29, 1, &MUX_GPIO29);
PINCTRL_DEVICE(GPIO30, 1, &MUX_GPIO30);
PINCTRL_DEVICE(GPIO31, 1, &MUX_GPIO31);
PINCTRL_DEVICE(GPIO32, 1, &MUX_GPIO32);
PINCTRL_DEVICE(GPIO33, 1, &MUX_GPIO33);
PINCTRL_DEVICE(GPIO34, 1, &MUX_GPIO34);
PINCTRL_DEVICE(GPIO35, 1, &MUX_GPIO35);
PINCTRL_DEVICE(GPIO36, 1, &MUX_GPIO36);
PINCTRL_DEVICE(GPIO37, 1, &MUX_GPIO37);
PINCTRL_DEVICE(GPIO38, 1, &MUX_GPIO38);
PINCTRL_DEVICE(GPIO39, 1, &MUX_GPIO39);
PINCTRL_DEVICE(GPIO40, 1, &MUX_GPIO40);
PINCTRL_DEVICE(GPIO41, 1, &MUX_GPIO41);
PINCTRL_DEVICE(GPIO42, 1, &MUX_GPIO42);
PINCTRL_DEVICE(GPIO43, 1, &MUX_GPIO43);
PINCTRL_DEVICE(GPIO44, 1, &MUX_GPIO44);
PINCTRL_DEVICE(GPIO45, 1, &MUX_GPIO45);
PINCTRL_DEVICE(GPIO46, 1, &MUX_GPIO46);
PINCTRL_DEVICE(GPIO47, 1, &MUX_GPIO47);
PINCTRL_DEVICE(GPIO48, 1, &MUX_GPIO48);
PINCTRL_DEVICE(GPIO49, 1, &MUX_GPIO49);
PINCTRL_DEVICE(GPIO50, 1, &MUX_GPIO50);
PINCTRL_DEVICE(GPIO51, 1, &MUX_GPIO51);
PINCTRL_DEVICE(GPIO52, 1, &MUX_GPIO52);
PINCTRL_DEVICE(GPIO53, 1, &MUX_GPIO53);
PINCTRL_DEVICE(GPIO54, 1, &MUX_GPIO54);
PINCTRL_DEVICE(GPIO55, 1, &MUX_GPIO55);
PINCTRL_DEVICE(GPIO56, 1, &MUX_GPIO56);
PINCTRL_DEVICE(GPIO57, 1, &MUX_GPIO57);
PINCTRL_DEVICE(GPIO61, 1, &MUX_GPIO61);
PINCTRL_DEVICE(GPIO62, 1, &MUX_GPIO62);
PINCTRL_DEVICE(GPIO63, 1, &MUX_GPIO63);


void fh_pinctrl_init_devicelist(OS_LIST *list)
{
    OS_LIST_EMPTY(list);

    PINCTRL_ADD_DEVICE(USB);
    PINCTRL_ADD_DEVICE(AC);
    PINCTRL_ADD_DEVICE(ACI2S);
    PINCTRL_ADD_DEVICE(DWI2S);
    PINCTRL_ADD_DEVICE(ARCJTAG);
    PINCTRL_ADD_DEVICE(ARMJTAG);
    PINCTRL_ADD_DEVICE(PAEJTAG);
    PINCTRL_ADD_DEVICE(CIS);
    PINCTRL_ADD_DEVICE(MIPI);
    PINCTRL_ADD_DEVICE(CIS_10BIT);

    PINCTRL_ADD_DEVICE(I2C0);
    PINCTRL_ADD_DEVICE(I2C1);
    PINCTRL_ADD_DEVICE(RMII);
    PINCTRL_ADD_DEVICE(PWM0);
    PINCTRL_ADD_DEVICE(PWM1);
    PINCTRL_ADD_DEVICE(PWM2);
    PINCTRL_ADD_DEVICE(PWM3);
    PINCTRL_ADD_DEVICE(PWM4);
    PINCTRL_ADD_DEVICE(PWM5);
    PINCTRL_ADD_DEVICE(PWM6);
    PINCTRL_ADD_DEVICE(PWM7);
    PINCTRL_ADD_DEVICE(SD0);
    PINCTRL_ADD_DEVICE(SD0_CARD_1BIT);
    PINCTRL_ADD_DEVICE(SD0_WIFI_2BIT);
    PINCTRL_ADD_DEVICE(SD1);
    PINCTRL_ADD_DEVICE(SSI0);
    PINCTRL_ADD_DEVICE(SSI1);
    PINCTRL_ADD_DEVICE(SSI2);
    PINCTRL_ADD_DEVICE(UART0);
    PINCTRL_ADD_DEVICE(UART1);
    PINCTRL_ADD_DEVICE(GPIO0);
    PINCTRL_ADD_DEVICE(GPIO1);
    PINCTRL_ADD_DEVICE(GPIO2);
    PINCTRL_ADD_DEVICE(GPIO3);
    PINCTRL_ADD_DEVICE(GPIO4);
    PINCTRL_ADD_DEVICE(GPIO5);
    PINCTRL_ADD_DEVICE(GPIO6);
    PINCTRL_ADD_DEVICE(GPIO7);
    PINCTRL_ADD_DEVICE(GPIO8);
    PINCTRL_ADD_DEVICE(GPIO9);
    PINCTRL_ADD_DEVICE(GPIO10);
    PINCTRL_ADD_DEVICE(GPIO11);
    PINCTRL_ADD_DEVICE(GPIO12);
    PINCTRL_ADD_DEVICE(GPIO13);
    PINCTRL_ADD_DEVICE(GPIO14);
    PINCTRL_ADD_DEVICE(GPIO15);
    PINCTRL_ADD_DEVICE(GPIO16);
    PINCTRL_ADD_DEVICE(GPIO17);
    PINCTRL_ADD_DEVICE(GPIO19);
    PINCTRL_ADD_DEVICE(GPIO20);
    PINCTRL_ADD_DEVICE(GPIO21);
    PINCTRL_ADD_DEVICE(GPIO22);
    PINCTRL_ADD_DEVICE(GPIO23);
    PINCTRL_ADD_DEVICE(GPIO24);
    PINCTRL_ADD_DEVICE(GPIO25);
    PINCTRL_ADD_DEVICE(GPIO26);
    PINCTRL_ADD_DEVICE(GPIO27);
    PINCTRL_ADD_DEVICE(GPIO28);
    PINCTRL_ADD_DEVICE(GPIO29);
    PINCTRL_ADD_DEVICE(GPIO30);
    PINCTRL_ADD_DEVICE(GPIO31);
    PINCTRL_ADD_DEVICE(GPIO32);
    PINCTRL_ADD_DEVICE(GPIO33);
    PINCTRL_ADD_DEVICE(GPIO34);
    PINCTRL_ADD_DEVICE(GPIO35);
    PINCTRL_ADD_DEVICE(GPIO36);
    PINCTRL_ADD_DEVICE(GPIO37);
    PINCTRL_ADD_DEVICE(GPIO38);
    PINCTRL_ADD_DEVICE(GPIO39);
    PINCTRL_ADD_DEVICE(GPIO40);
    PINCTRL_ADD_DEVICE(GPIO41);
    PINCTRL_ADD_DEVICE(GPIO42);
    PINCTRL_ADD_DEVICE(GPIO43);
    PINCTRL_ADD_DEVICE(GPIO44);
    PINCTRL_ADD_DEVICE(GPIO45);
    PINCTRL_ADD_DEVICE(GPIO46);
    PINCTRL_ADD_DEVICE(GPIO47);
    PINCTRL_ADD_DEVICE(GPIO48);
    PINCTRL_ADD_DEVICE(GPIO49);
    PINCTRL_ADD_DEVICE(GPIO50);
    PINCTRL_ADD_DEVICE(GPIO51);
    PINCTRL_ADD_DEVICE(GPIO52);
    PINCTRL_ADD_DEVICE(GPIO53);
    PINCTRL_ADD_DEVICE(GPIO54);
    PINCTRL_ADD_DEVICE(GPIO55);
    PINCTRL_ADD_DEVICE(GPIO56);
    PINCTRL_ADD_DEVICE(GPIO57);
    PINCTRL_ADD_DEVICE(GPIO61);
    PINCTRL_ADD_DEVICE(GPIO62);
    PINCTRL_ADD_DEVICE(GPIO63);
}



char* fh_pinctrl_selected_devices[] =
{
	CONFIG_PINCTRL_SELECT
};
