#
# Makefile for Hisilicon processors family
#

obj-$(CONFIG_ARCH_HI3516A) += mach-hi3516a.o
obj-$(CONFIG_ARCH_HI3518EV20X) += mach-hi3518ev20x.o
obj-$(CONFIG_ARCH_HI3536DV100) += mach-hi3536dv100.o
obj-$(CONFIG_ARCH_HI3521A) += mach-hi3521a.o
obj-$(CONFIG_ARCH_HI3531A) += mach-hi3531a.o

obj-$(CONFIG_CACHE_L2X0)   += l2cache.o

obj-$(CONFIG_SMP)	+= platsmp.o
