dtb-$(CONFIG_ARCH_HISI) += hi6220-hikey.dtb
dtb-$(CONFIG_ARCH_HISI) += hip05-d02.dtb
dtb-$(CONFIG_ARCH_HISI) += hip06-d03.dtb
dtb-$(CONFIG_ARCH_HI3559AV100)	+= hi3559av100-demb-flash.dtb
dtb-$(CONFIG_ARCH_HI3559AV100)	+= hi3559av100-demb-emmc.dtb
dtb-$(CONFIG_ARCH_HI3559AV100)	+= hi3559av100-demb-ufs.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
