EXTRA_CFLAGS += -Idrivers/mstar/include

obj-y += ms_composite_clk.o
obj-$(CONFIG_MS_USCLK)=ms_usclk.o
obj-$(CONFIG_ARCH_CEDRIC) += cedric/
obj-$(CONFIG_ARCH_INFINITY) += infinity/
obj-$(CONFIG_ARCH_INFINITY3) += infinity3/
