#
# Makefile for the Faraday device drivers.
#

obj-$(CONFIG_FTGMAC100) += gmac100.o
obj-$(CONFIG_FTGMAC030) += gmac030.o
obj-$(CONFIG_FTMAC110) += ftmac110.o
gmac100-objs		:= ftgmac100_platform.o ftgmac100.o
gmac030-objs		:= ftgmac030_platform.o ftgmac030.o #ptp.o