# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_HI3xxx) += \
	hi3620-hi4511.dtb
dtb-$(CONFIG_ARCH_HIP01) += \
	hip01-ca9x2.dtb
dtb-$(CONFIG_ARCH_HIP04) += \
	hip04-d01.dtb
dtb-$(CONFIG_ARCH_HISI) += \
	hi3519-demb.dtb
dtb-$(CONFIG_ARCH_HIX5HD2) += \
	hisi-x5hd2-dkb.dtb
dtb-$(CONFIG_ARCH_SD5203) += \
	sd5203.dtb
dtb-$(CONFIG_ARCH_HISI_BVT) += \
	hi3516ev200-demb.dtb \
	hi3516ev300-demb.dtb \
	hi3518ev300-demb.dtb \
	hi3518ev20x-demb.dtb
dtb-$(CONFIG_ARCH_HI3516DV300) += \
	hi3516dv300-demb.dtb
dtb-$(CONFIG_ARCH_HI3516CV300) += \
	hi3516cv300-demb.dtb
dtb-$(CONFIG_ARCH_HI3516CV200) += \
	hi3516cv200-demb.dtb
dtb-$(CONFIG_ARCH_HI3516CV100) += \
	hi3516cv100-demb.dtb
dtb-$(CONFIG_ARCH_HI3516AV100) += \
	hi3516av100-demb.dtb
