#define RO 0
#define RW 1
#if defined(_VHE_REGS_TABLE_)
#define VHEREG(name,idx,bits,trc,wr,comment)    {(2U<<(1?bits))-(1U<<(0?bits)),(0?bits),idx,trc,wr}
#else
#define VHEREG(name,idx,bits,trc,wr,comment)    name
#endif
VHEREG(HWIF_PRODUCT_ID                                     , 0,31:16,0,RO,"Product ID"),
VHEREG(HWIF_MAJOR_NUMBER                                   , 0,15: 8,0,RO,"Major number"),
VHEREG(HWIF_MINOR_NUMBER                                   , 0, 7: 0,0,RO,"Minor number"),
VHEREG(HWIF_ENC_TIMEOUT_INT                                , 1,11:11,0,RW,"enable timeout interrupt when 1"),
VHEREG(HWIF_ENC_SLICE_RDY_STATUS                           , 1, 8: 8,0,RW,"Interrupt status bit encoder. When this bit is high encoder has encoded a slice."),
VHEREG(HWIF_ENC_TIMEOUT                                    , 1, 6: 6,0,RW,"Interrupt status bit encoder timeout. When high the encoder has been idling for too long. Possible only if timeout interrupt is enabled"),
VHEREG(HWIF_ENC_BUFFER_FULL                                , 1, 5: 5,1,RW,"IRQ buffer full status bit. bufferFullInterrupt"),
VHEREG(HWIF_ENC_SW_RESET                                   , 1, 4: 4,0,RW,"IRQ SW reset status bit."),
VHEREG(HWIF_ENC_BUS_ERROR_STATUS                           , 1, 3: 3,0,RW,"Interrupt status bit bus. Error response from bus. "),
VHEREG(HWIF_ENC_FRAME_RDY_STATUS                           , 1, 2: 2,0,RW,"Interrupt status bit encoder. When this bit is high encoder has encoded a picture."),
VHEREG(HWIF_ENC_IRQ_DIS                                    , 1, 1: 1,0,RW,"Encoder IRQ disable. When high  there are no interrupts concerning encoder from HW. Polling must be used to see the interrupt statuses."),
VHEREG(HWIF_ENC_IRQ                                        , 1, 0: 0,0,RW,"Encoder IRQ. When high  encoder requests an interrupt. SW will reset this after interrupt is handled."),
VHEREG(HWIF_ENC_AXI_WRITE_ID                               , 2,31:24,0,RW,"AXI Write ID"),
VHEREG(HWIF_ENC_AXI_READ_ID                                , 2,23:16,0,RW,"AXI Read ID"),
VHEREG(HWIF_ENC_STRM_SWAP                                  , 2,15:12,0,RW,"byte swap config for output stream data.4 Bit byte order vector to control byte locations inside HW internal 128 bit data vector. For 64 and 32 bit external bus widths the data is forst gathered to 128 bit width and then bytes swapped accordingly"),
VHEREG(HWIF_ENC_PIC_SWAP                                   , 2,11: 8,0,RW,"Byte swap configuration for picture data (encoder input)"),
VHEREG(HWIF_ENC_BURST_DISABLE                              , 3,31:31,0,RW,"Disable burst mode for AXI"),
VHEREG(HWIF_ENC_BURST_INCR                                 , 3,30:30,0,RW,"Burst incremental. 1=INCR burst allowed. 0=use SINGLE burst"),
VHEREG(HWIF_ENC_DATA_DISCARD                               , 3,29:29,0,RW,"Enable burst data discard. 2 or 3 long reads are using BURST4"),
VHEREG(HWIF_ENC_CLOCK_GATING                               , 3,28:28,0,RW,"Enable clock gating"),
VHEREG(HWIF_ENC_INPUT_READ_CHUNK                           , 3,27:27,0,RW,"Chunk size for input picture read 0=4 MBs. 1=1 MB"),
VHEREG(HWIF_ENC_AXI_DUAL_CH                                , 3,26:26,0,RW,"Disable dual channel AXI. 0=use two channels. 1=use single channel."),
VHEREG(HWIF_ENC_AXI_WR_ID_E                                , 3,25:25,0,RW,"axi write enable 0=disable. 1=enable."),
VHEREG(HWIF_ENC_AXI_RD_ID_E                                , 3,24:24,0,RW,"axi read enable 0=disable. 1=enable."),
VHEREG(HWIF_ENC_SLICE_INT                                  , 3, 3: 3,1,RW,"enable slice interrupt when 1"),
VHEREG(HWIF_ENC_MODE                                       , 4,31:29,1,RW,"Encoding mode. streamType.1= hevc"),
VHEREG(HWIF_ENC_MIN_CB_SIZE                                , 4,26:25,0,RO,"min cb size:0-8x8:1-16x16:2-32x32:3-64x64:we only support 8x8"),
VHEREG(HWIF_ENC_MAX_CB_SIZE                                , 4,24:23,0,RO,"max cb size:0-8x8:1-16x16:2-32x32:3-64x64:we only support 64x64"),
VHEREG(HWIF_ENC_MIN_TRB_SIZE                               , 4,22:21,0,RO,"min tr block size:0-4x4:1-8x8:2-16x16:3-32x32:we only support 4x4"),
VHEREG(HWIF_ENC_MAX_TRB_SIZE                               , 4,20:19,0,RO,"max tr block size:0-4x4:1-8x8:2-16x16:3-32x32:we only support 16x16"),
VHEREG(HWIF_ENC_OUTPUT_STRM_MODE                           , 4,18:18,1,RW,"output stream mode:0-byte stream:1-Nal stream"),
VHEREG(HWIF_ENC_CHROMA_QP_OFFSET                           , 4,17:13,0,RW,"chroma qp offset[-12~12]"),
VHEREG(HWIF_ENC_STRONG_INTRA_SMOOTHING_ENABLED_FLAG        , 4,12:12,0,RW,"strong intra smoothing enabled flag"),
VHEREG(HWIF_ENC_CONSTRAINED_INTRA_PRED_FLAG                , 4,11:11,0,RW,"constrained intra pred flag"),
VHEREG(HWIF_ENC_SCALING_LIST_ENABLED_FLAG                  , 4, 8: 8,0,RW,"scaling_list_enabled_flag"),
VHEREG(HWIF_ENC_ACTIVE_OVERRIDE_FLAG                       , 4, 7: 7,0,RW,"active override flag"),
VHEREG(HWIF_ENC_SAO_ENABLE                                 , 4, 6: 6,0,RW,"SAO enable"),
VHEREG(HWIF_ENC_MAX_TRANS_HIERARCHY_DEPTH_INTRA            , 4, 5: 3,0,RO,"max transform hierarchy depth of intra"),
VHEREG(HWIF_ENC_MAX_TRANS_HIERARCHY_DEPTH_INTER            , 4, 2: 0,0,RO,"max transform hierarchy depth of inter "),
VHEREG(HWIF_ENC_PIC_WIDTH                                  , 5,31:22,1,RW,"Encoded width. lumWidth(unit 8 pixels)"),
VHEREG(HWIF_ENC_PIC_HEIGHT                                 , 5,21:11,1,RW,"Encoded height. lumHeight(unit 8 pixels):Max width x height is 4096 x 4096"),
VHEREG(HWIF_ENC_PPS_DEBLOCKING_FILTER_OVERRIDE_ENABLED_FLAG, 5, 9: 9,0,RW,"deblocking filter override enable flag.0:disable 1:enable"),
VHEREG(HWIF_ENC_SLICE_DEBLOCKING_FILTER_OVERRIDE_FLAG      , 5, 8: 8,0,RW,"slice deblocking filter override flag.0:no 1:yes"),
VHEREG(HWIF_ENC_BUFFER_FULL_CONTINUE                       , 5, 5: 5,0,RW,"continue to encode the same frame after buffer full.0:not continue 1:continue"),
VHEREG(HWIF_ENC_REF_FRAMES                                 , 5, 4: 3,0,RW,"HEVC: num_ref_frames  maximum number of short and long term reference frames in encoded picture buffer"),
VHEREG(HWIF_ENC_FRAME_CODING_TYPE                          , 5, 2: 1,1,RW,"Encoded picture type. frameType.:1-I:0-P:2-B"),
VHEREG(HWIF_ENC_TRIGGER                                    , 5, 0: 0,0,RW,"encoder enable. Setting this bit high will start the encoding operation. HW will reset this when picture is processed or bus error or timeout interrupt is given."),
VHEREG(HWIF_ENC_SLICE_SIZE                                 , 6,31:25,1,RW,"slice size in ctu row"),
VHEREG(HWIF_ENC_NUM_SHORT_TERM_REF_PIC_SETS                , 6,24:22,0,RW,"number of short term reference picture sets"),
VHEREG(HWIF_ENC_NUM_NEGATIVE_PICS                          , 6,19:18,0,RW,"number of negative pictures"),
VHEREG(HWIF_ENC_NUM_POSITIVE_PICS                          , 6,17:16,0,RW,"number of positive pictures"),
VHEREG(HWIF_ENC_DEBLOCKING_FILTER_CTRL                     , 6,15:15,0,RW,"deblocking filter control.De-block filtering disable: 1 = filtering is disabled for current picture. 0 = filtering is enabled for current picture"),
VHEREG(HWIF_ENC_DEBLOCKING_TC_OFFSET                       , 6,14:11,0,RW,"deblocking tc offset:-6~6"),
VHEREG(HWIF_ENC_DEBLOCKING_BETA_OFFSET                     , 6,10: 7,0,RW,"deblocking beta offset:-6~6"),
VHEREG(HWIF_ENC_RPS_ID                                     , 6, 4: 2,0,RW,"rps Id:used for slice header"),
VHEREG(HWIF_ENC_NAL_SIZE_WRITE                             , 6, 1: 1,1,RW,"Enable writing size of each NAL unit to BaseControl"),
VHEREG(HWIF_ENC_CU_QP_DELTA_ENABLED                        , 6, 0: 0,0,RW,"cu qp delta encoding is enabled:used for ROI"),
VHEREG(HWIF_ENC_PIC_INIT_QP                                , 7,31:26,1,RW,"picture header qp"),
VHEREG(HWIF_ENC_CABAC_INIT_FLAG                            , 7,25:25,0,RW,"cabac init flag"),
VHEREG(HWIF_ENC_NUM_SLICES_READY                           , 7,24:17,0,RW,"HEVC amount of completed slices."),
VHEREG(HWIF_ENC_PIC_QP                                     , 7,13: 8,1,RW,"qp of current picture"),
VHEREG(HWIF_ENC_ROI1_DELTA_QP                              , 7, 7: 4,0,RW,"ROI1 delta qp"),
VHEREG(HWIF_ENC_ROI2_DELTA_QP                              , 7, 3: 0,0,RW,"ROI2 delta qp"),
VHEREG(HWIF_ENC_OUTPUT_STRM_BASE                           , 8,31: 0,0,RW,"output stream base address"),
VHEREG(HWIF_ENC_OUTPUT_STRM_BUFFER_LIMIT                   , 9,31: 0,1,RW,"Stream buffer limit (64bit addresses) / output stream size (bits). HWStreamDataCount. If limit is reached buffer full IRQ is given."),
VHEREG(HWIF_ENC_SIZE_TBL_BASE                              ,10,31: 0,0,RW,"sizeTblBase"),
VHEREG(HWIF_ENC_POC                                        ,11,31: 0,0,RW,"encoded Picture order count"),
VHEREG(HWIF_ENC_INPUT_Y_BASE                               ,12,31: 0,0,RW,"input image lum base address"),
VHEREG(HWIF_ENC_INPUT_CB_BASE                              ,13,31: 0,0,RW,"input image cb base address "),
VHEREG(HWIF_ENC_INPUT_CR_BASE                              ,14,31: 0,0,RW,"input image cr base address "),
VHEREG(HWIF_ENC_RECON_Y_BASE                               ,15,31: 0,0,RW,"recon image lum base address"),
VHEREG(HWIF_ENC_RECON_CHROMA_BASE                          ,16,31: 0,0,RW,"recon image chroma base address"),
VHEREG(HWIF_ENC_DELTA_POC0                                 ,17,31:22,0,RW,"delta of poc0"),
VHEREG(HWIF_ENC_USED_BY_CURR_PIC0                          ,17,20:20,0,RW,"used by current pic0"),
VHEREG(HWIF_ENC_DELTA_POC1                                 ,17,19:10,0,RW,"delta of poc1"),
VHEREG(HWIF_ENC_USED_BY_CURR_PIC1                          ,17, 8: 8,0,RW,"used by current pic1"),
VHEREG(HWIF_ENC_ACTIVE_L0_CNT                              ,17, 7: 6,0,RW,"active l0 count"),
VHEREG(HWIF_ENC_RECON_LUMA_COMPRESSOR_ENABLE               ,17, 5: 5,1,RW,"recon frame luma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_RECON_CHROMA_COMPRESSOR_ENABLE             ,17, 4: 4,1,RW,"recon frame chroma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_L0_REF0_LUMA_COMPRESSOR_ENABLE             ,17, 3: 3,1,RW,"ref0 frame luma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_L0_REF0_CHROMA_COMPRESSOR_ENABLE           ,17, 2: 2,1,RW,"ref0 frame chroma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_L0_REF1_LUMA_COMPRESSOR_ENABLE             ,17, 1: 1,1,RW,"ref1 frame luma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_L0_REF1_CHROMA_COMPRESSOR_ENABLE           ,17, 0: 0,1,RW,"ref1 frame chroma compressor enable flag 0=disable 1=enable."),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_Y0                         ,18,31: 0,0,RW,"reference picture reconstructed list0 luma0"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_CHROMA0                    ,19,31: 0,0,RW,"reference picture reconstructed list0 chroma0"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_Y1                         ,20,31: 0,0,RW,"reference picture reconstructed list0 luma1"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_CHROMA1                    ,21,31: 0,0,RW,"reference picture reconstructed list0 chroma1"),
VHEREG(HWIF_ENC_CIR_START                                  ,22,31:18,0,RW,"cir start"),
VHEREG(HWIF_ENC_CIR_INTERVAL                               ,22,17: 4,0,RW,"Cyclic Intra Refresh"),
VHEREG(HWIF_ENC_INTRA_AREA_LEFT                            ,23,31:24,0,RW,"intra Area Left"),
VHEREG(HWIF_ENC_INTRA_AREA_RIGHT                           ,23,23:16,0,RW,"intra Area Right"),
VHEREG(HWIF_ENC_INTRA_AREA_TOP                             ,23,15: 8,0,RW,"intra Area Top"),
VHEREG(HWIF_ENC_INTRA_AREA_BOTTOM                          ,23, 7: 0,0,RW,"intra Area Bottom"),
VHEREG(HWIF_ENC_ROI1_LEFT                                  ,24,31:24,0,RW,"ROI1 Area Left"),
VHEREG(HWIF_ENC_ROI1_RIGHT                                 ,24,23:16,0,RW,"ROI1 Area Right"),
VHEREG(HWIF_ENC_ROI1_TOP                                   ,24,15: 8,0,RW,"ROI1 Area Top"),
VHEREG(HWIF_ENC_ROI1_BOTTOM                                ,24, 7: 0,0,RW,"ROI1 Area Bottom"),
VHEREG(HWIF_ENC_ROI2_LEFT                                  ,25,31:24,0,RW,"ROI2 Area Left"),
VHEREG(HWIF_ENC_ROI2_RIGHT                                 ,25,23:16,0,RW,"ROI2 Area Right"),
VHEREG(HWIF_ENC_ROI2_TOP                                   ,25,15: 8,0,RW,"ROI2 Area Top"),
VHEREG(HWIF_ENC_ROI2_BOTTOM                                ,25, 7: 0,0,RW,"ROI2 Area Bottom"),
VHEREG(HWIF_ENC_INTRA_PENALTY_PIC4X4                       ,26,31:19,0,RW,"intra penalty for pic4x4"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_PIC1                     ,26,18:10,0,RW,"intra MPM penalty for pic1"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_PIC2                     ,26, 9: 0,0,RW,"intra MPM penalty for pic2"),
VHEREG(HWIF_ENC_INTRA_PENALTY_PIC8X8                       ,27,31:19,0,RW,"intra penalty for pic8x8"),
VHEREG(HWIF_ENC_INTRA_PENALTY_PIC16X16                     ,27,18: 5,0,RW,"intra penalty for pic16x16"),
VHEREG(HWIF_ENC_INTRA_PENALTY_PIC32X32                     ,28,31:18,0,RW,"intra penalty for pic32x32"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_PIC3                     ,28,17: 7,0,RW,"intra MPM penalty for pic3"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI14X4                      ,29,31:19,0,RW,"intra penalty for roi14x4"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI11                    ,29,18:10,0,RW,"intra MPM penalty for roi11"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI12                    ,29, 9: 0,0,RW,"intra MPM penalty for roi12"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI18X8                      ,30,31:19,0,RW,"intra penalty for roi18x8"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI116X16                    ,30,18: 5,0,RW,"intra penalty for roi116x16"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI132X32                    ,31,31:18,0,RW,"intra penalty for roi132x32"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI13                    ,31,17: 7,0,RW,"intra MPM penalty for roi13"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI24X4                      ,32,31:19,0,RW,"intra penalty for roi24x4"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI21                    ,32,18:10,0,RW,"intra MPM penalty for roi21"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI22                    ,32, 9: 0,0,RW,"intra MPM penalty for roi22"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI28X8                      ,33,31:19,0,RW,"intra penalty for roi28x8"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI216X16                    ,33,18: 5,0,RW,"intra penalty for roi216x16"),
VHEREG(HWIF_ENC_INTRA_PENALTY_ROI232X32                    ,34,31:18,0,RW,"intra penalty for roi232x32"),
VHEREG(HWIF_ENC_INTRA_MPM_PENALTY_ROI23                    ,34,17: 7,0,RW,"intra MPM penalty for roi23"),
VHEREG(HWIF_ENC_LAMBDA_MOTIONSAD                           ,34, 6: 0,0,RW,"lamda for motion SAD"),
VHEREG(HWIF_ENC_LAMDA_MOTION_SSE                           ,35,31:18,0,RW,"lambda for motion SSE"),
VHEREG(HWIF_ENC_BITS_EST_TU_SPLIT_PENALTY                  ,35,17:15,0,RW,"bits estimation for tu split penalty"),
VHEREG(HWIF_ENC_BITS_EST_BIAS_INTRA_CU_8                   ,35,14: 8,0,RW,"bits estimation bias for intra cu 8"),
VHEREG(HWIF_ENC_BITS_EST_BIAS_INTRA_CU_16                  ,35, 7: 0,0,RW,"bits estimation bias for intra cu 16"),
VHEREG(HWIF_ENC_BITS_EST_BIAS_INTRA_CU_32                  ,36,31:23,0,RW,"bits estimation bias for intra cu 32"),
VHEREG(HWIF_ENC_BITS_EST_BIAS_INTRA_CU_64                  ,36,22:13,0,RW,"bits estimation bias for intra cu 64"),
VHEREG(HWIF_ENC_INTER_SKIP_BIAS                            ,36,12: 6,0,RW,"inter skip bias"),
VHEREG(HWIF_ENC_BITS_EST_1N_CU_PENALTY                     ,36, 5: 2,0,RW,"bits estimation 1N cu penalty"),
VHEREG(HWIF_ENC_LAMDA_SAO_CHROMA                           ,37,31:18,0,RW,"lambda for SAO chroma"),
VHEREG(HWIF_ENC_LAMDA_SAO_LUMA                             ,37,17: 4,0,RW,"lambda for SAO luma"),
VHEREG(HWIF_ENC_CHROFFSET                                  ,37, 3: 0,0,RW,"Input chrominance offset (bytes) [0..15]"),
VHEREG(HWIF_ENC_INPUT_FORMAT                               ,38,31:28,1,RW,"Input image format. inputFormat. YUV420P/YUV420SP/YUYV422/UYVY422/RGB565/RGB555/RGB444/RGB888/RGB101010"),
VHEREG(HWIF_ENC_INPUT_ROTATION                             ,38,27:26,1,RW,"Input image rotation. 0=disabled. 1=90 degrees right. 2=90 degrees left"),
VHEREG(HWIF_ENC_LUMOFFSET                                  ,38,23:20,0,RW,"Input luminance offset (bytes) [0..15]"),
VHEREG(HWIF_ENC_ROWLENGTH                                  ,38,19: 6,1,RW,"Input luminance row length. lumWidthSrc (bytes) [96..8192]"),
VHEREG(HWIF_ENC_XFILL                                      ,38, 5: 4,0,RW,"Overfill pixels on right edge of image div2 [0.1.2.3]"),
VHEREG(HWIF_ENC_YFILL                                      ,38, 3: 1,1,RW,"Overfill pixels on bottom edge of image. YFill. [0бн7]"),
VHEREG(HWIF_ENC_RGBCOEFFA                                  ,39,31:16,0,RW,"RGB to YUV conversion coefficient A"),
VHEREG(HWIF_ENC_RGBCOEFFB                                  ,39,15: 0,0,RW,"RGB to YUV conversion coefficient B"),
VHEREG(HWIF_ENC_RGBCOEFFC                                  ,40,31:16,0,RW,"RGB to YUV conversion coefficient C"),
VHEREG(HWIF_ENC_RGBCOEFFE                                  ,40,15: 0,0,RW,"RGB to YUV conversion coefficient D"),
VHEREG(HWIF_ENC_RGBCOEFFF                                  ,41,31:16,0,RW,"RGB to YUV conversion coefficient E"),
VHEREG(HWIF_ENC_RMASKMSB                                   ,41,15:11,0,RW,"RGB R-component mask MSB bit position [0..31]"),
VHEREG(HWIF_ENC_GMASKMSB                                   ,41,10: 6,0,RW,"RGB G-component mask MSB bit position [0..31]"),
VHEREG(HWIF_ENC_BMASKMSB                                   ,41, 5: 1,0,RW,"RGB B-component mask MSB bit position [0..31]"),
VHEREG(HWIF_ENC_BASESCALEDOUTLUM                           ,42,31: 0,0,RW,"Base address for output of down-scaled encoder image in YUYV 4:2:2 format"),
VHEREG(HWIF_ENC_SCALEDOUTWIDTH                             ,43,31:19,1,RW,"Scaling width of down-scaled image. ScaledWidth. [96..4076]"),
VHEREG(HWIF_ENC_SCALEDOUTWIDTHRATIO                        ,43,18: 3,0,RW,"Scaling ratio for width of down-scaled image. Fixed point integer 1.16."),
VHEREG(HWIF_ENC_SCALE_MODE                                 ,43, 1: 0,1,RW,"Scaling mode. ScalingMode. 0=disabled. 1=scaling only. 2=scale+encode"),
VHEREG(HWIF_ENC_SCALEDOUTHEIGHT                            ,44,31:18,1,RW,"Scaling width of down-scaled image. ScaledHeight. [2..4078]"),
VHEREG(HWIF_ENC_SCALEDOUTHEIGHTRATIO                       ,44,17: 2,0,RW,"Scaling ratio for height of down-scaled image. Fixed point integer 1.16."),
VHEREG(HWIF_ENC_SCALEDOUT_SWAP                             ,45,31:28,0,RW,"Byte swap configuration for scaledout data (scaledout)"),
VHEREG(HWIF_ENC_CHROMA_SWAP                                ,45,27:27,1,RW,"Swap order of chroma bytes in semiplanar input format."),
VHEREG(HWIF_ENC_ENCODED_CTB_NUMBER                         ,45,26:14,0,RW,"MB count output. max 64*64"),
VHEREG(HWIF_ENC_SCALEDSKIPLEFTPIXELCOLUMN                  ,45,13:12,0,RW,"skip left pixel column"),
VHEREG(HWIF_ENC_SCALEDSKIPTOPPIXELROW                      ,45,11:10,0,RW,"skip top pixel row"),
VHEREG(HWIF_ENC_VSCALE_WEIGHT_EN                           ,45, 9: 9,0,RW,"vertical scale weight enable."),
VHEREG(HWIF_ENC_SCALEDHORIZONTALCOPY                       ,45, 8: 8,0,RW,"horizontal data copy directly"),
VHEREG(HWIF_ENC_SCALEDVERTICALCOPY                         ,45, 7: 7,0,RW,"vertical data copy directly"),
VHEREG(HWIF_ENC_COMPRESSEDCOEFF_BASE                       ,46,31: 0,0,RW,"Base address for compressed coefficients."),
VHEREG(HWIF_ENC_COMPRESSEDCOEFF_BASE_MSB                   ,47,31: 0,0,RW,"Base address MSB for compressed coefficients."),
VHEREG(HWIF_ENC_BASESCALEDOUTLUM_MSB                       ,48,31: 0,0,RW,"Base address MSB for output of down-scaled encoder image in YUYV 4:2:2 format"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_Y0_MSB                     ,49,31: 0,0,RW,"reference picture reconstructed list0 luma0 MSB"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_CHROMA0_MSB                ,50,31: 0,0,RW,"reference picture reconstructed list0 chroma0 MSB"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_Y1_MSB                     ,51,31: 0,0,RW,"reference picture reconstructed list0 luma1 MSB"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_CHROMA1_MSB                ,52,31: 0,0,RW,"reference picture reconstructed list0 chroma1 MSB"),
VHEREG(HWIF_ENC_INPUT_Y_BASE_MSB                           ,53,31: 0,0,RW,"input image lum base address MSB"),
VHEREG(HWIF_ENC_INPUT_CB_BASE_MSB                          ,54,31: 0,0,RW,"input image cb base address MSB"),
VHEREG(HWIF_ENC_INPUT_CR_BASE_MSB                          ,55,31: 0,0,RW,"input image cr base address MSB"),
VHEREG(HWIF_ENC_RECON_Y_BASE_MSB                           ,56,31: 0,0,RW,"recon image lum base address MSB"),
VHEREG(HWIF_ENC_RECON_CHROMA_BASE_MSB                      ,57,31: 0,0,RW,"recon image chroma base address MSB"),
VHEREG(HWIF_ENC_SIZE_TBL_BASE_MSB                          ,58,31: 0,0,RW,"sizeTblBase MSB"),
VHEREG(HWIF_ENC_OUTPUT_STRM_BASE_MSB                       ,59,31: 0,0,RW,"output stream base address MSB"),
VHEREG(HWIF_ENC_RECON_LUMA_COMPRESS_TABLE_BASE             ,60,31: 0,0,RW,"Base address for recon luma compress table LSB."),
VHEREG(HWIF_ENC_RECON_LUMA_COMPRESS_TABLE_BASE_MSB         ,61,31: 0,0,RW,"Base address for recon luma compress table MSB."),
VHEREG(HWIF_ENC_RECON_CHROMA_COMPRESS_TABLE_BASE           ,62,31: 0,0,RW,"Base address for recon Chroma compress table LSB."),
VHEREG(HWIF_ENC_RECON_CHROMA_COMPRESS_TABLE_BASE_MSB       ,63,31: 0,0,RW,"Base address for recon Chroma compress table MSB."),
VHEREG(HWIF_ENC_L0_REF0_LUMA_COMPRESS_TABLE_BASE           ,64,31: 0,0,RW,"Base address for list 0 ref 0 luma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF0_LUMA_COMPRESS_TABLE_BASE_MSB       ,65,31: 0,0,RW,"Base address for list 0 ref 0 luma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF0_CHROMA_COMPRESS_TABLE_BASE         ,66,31: 0,0,RW,"Base address for list 0 ref 0 Chroma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF0_CHROMA_COMPRESS_TABLE_BASE_MSB     ,67,31: 0,0,RW,"Base address for list 0 ref 0 Chroma compress table MSB."),
VHEREG(HWIF_ENC_L0_REF1_LUMA_COMPRESS_TABLE_BASE           ,68,31: 0,0,RW,"Base address for list 0 ref 1 luma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF1_LUMA_COMPRESS_TABLE_BASE_MSB       ,69,31: 0,0,RW,"Base address for list 0 ref 1 luma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF1_CHROMA_COMPRESS_TABLE_BASE         ,70,31: 0,0,RW,"Base address for list 0 ref 1 Chroma compress table LSB."),
VHEREG(HWIF_ENC_L0_REF1_CHROMA_COMPRESS_TABLE_BASE_MSB     ,71,31: 0,0,RW,"Base address for list 0 ref 1 Chroma compress table MSB."),
VHEREG(HWIF_ENC_RECON_LUMA_4N_BASE                         ,72,31: 0,0,RW,"Base address for recon luma 4n base LSB."),
VHEREG(HWIF_ENC_RECON_LUMA_4N_BASE_MSB                     ,73,31: 0,0,RW,"Base address for recon luma 4n base MSB."),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_4N0_BASE                   ,74,31: 0,0,RW,"reference picture reconstructed list0 4n 0"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_4N0_BASE_MSB               ,75,31: 0,0,RW,"reference picture reconstructed list0 4n 0 MSB"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_4N1_BASE                   ,76,31: 0,0,RW,"reference picture reconstructed list0 4n 1"),
VHEREG(HWIF_ENC_REFPIC_RECON_L0_4N1_BASE_MSB               ,77,31: 0,0,RW,"reference picture reconstructed list0 4n 1 MSB"),
VHEREG(HWIF_ENC_LAMDA_MOTION_SSE_ROI1                      ,78,31:18,0,RW,"roi1 lambda for motion SSE"),
VHEREG(HWIF_ENC_LAMDA_MOTION_SSE_ROI2                      ,78,17: 4,0,RW,"roi2 lambda for motion SSE"),
VHEREG(HWIF_ENC_SKIP_CHROMA_DC_THREADHOLD                  ,78, 1: 0,0,RW,"skip chroma dc threadhold"),
VHEREG(HWIF_ENC_LAMBDA_MOTIONSAD_ROI1                      ,79,31:25,0,RW,"roi1 lamda for motion SAD"),
VHEREG(HWIF_ENC_LAMBDA_MOTIONSAD_ROI2                      ,79,24:18,0,RW,"roi2 lamda for motion SAD"),
VHEREG(HWIF_ENC_HWCHSEARCHAREA                             ,80,31:31,0,RO,"HW Chrominance search area internal buffer. 0=not supported. 1=supported."),
VHEREG(HWIF_ENC_HWSCALINGSUPPORT                           ,80,30:30,0,RO,"Down-scaling supported by HW. 0=not supported. 1=supported"),
VHEREG(HWIF_ENC_HWSEARCHAREA                               ,80,29:29,0,RO,"HW search area height. 0=5 MB rows. 1=3 MB rows"),
VHEREG(HWIF_ENC_HWRGBSUPPORT                               ,80,28:28,0,RO,"RGB to YUV conversion supported by HW. 0=not supported. 1=supported"),
VHEREG(HWIF_ENC_HWHEVCSUPPORT                              ,80,27:27,0,RO,"HEVC encoding supported by HW. 0=not supported. 1=supported"),
VHEREG(HWIF_ENC_HWVP9SUPPORT                               ,80,26:26,0,RO,"VP9 encoding supported by HW. 0=not supported. 1=supported"),
VHEREG(HWIF_ENC_HWSTABSUPPORT                              ,80,25:25,0,RO,"Stabilization supported by HW. 0=not supported. 1=supported"),
VHEREG(HWIF_ENC_HWBUS                                      ,80,24:21,0,RO,"Bus connection of HW. 1=AHB. 2=OCP. 3=AXI. 4=PCI. 5=AXIAHB. 6=AXIAPB."),
VHEREG(HWIF_ENC_HWSYNTHESISLAN                             ,80,20:17,0,RO,"Synthesis language. 1=vhdl. 2=verilog"),
VHEREG(HWIF_ENC_HWBUSWIDTH                                 ,80,16:13,0,RO,"Bus width of HW. 0=32b. 1=64b. 2=128b"),
VHEREG(HWIF_ENC_HWMAXVIDEOWIDTH                            ,80,12: 0,0,RO,"Maximum video width supported by HW (pixels)"),
VHEREG(HWIF_ENC_MAX_BURST                                  ,81,31:24,0,RW,"for support AXI4.0 burst length is programmable Default value:0x10"),
VHEREG(HWIF_TIMEOUT_OVERRIDE_E                             ,81,23:23,0,RW,"enable signal if timeout period is controlled by software Default value: 0x0"),
VHEREG(HWIF_TIMEOUT_CYCLES                                 ,81,22: 0,0,RW,"timeout cycles number default value: 0x0"),
VHEREG(HWIF_ENC_HW_PERFORMANCE                             ,82,31: 0,0,RO,"record hardware  performance(cycles) of current picture"),
VHEREG(HWIF_ENTRIES,0,0:1,0,RO,"Invalid VHE_REG Field"),
#undef VHEREG
#undef RO
#undef RW
