#
# Makefile for the linux YAFFS filesystem routines.
#

obj-$(CONFIG_YAFFS_FS) += yaffs2multi.o

#	yaffs2-y := yaffs_mtdif_single.o
#	yaffs2-y += yaffs_packedtags1.o
#	yaffs2-y += yaffs_ecc.o yaffs_vfs_single.o yaffs_guts.o
#	yaffs2-y += yaffs_packedtags2.o
#	yaffs2-y += yaffs_tagscompat.o
#	yaffs2-y += yaffs_tagsmarshall.o
#	yaffs2-y += yaffs_checkptrw.o yaffs_nand.o
#	yaffs2-y += yaffs_checkptrw.o yaffs_nand.o yaffs_nameval.o
#	yaffs2-y += yaffs_allocator.o yaffs_bitmap.o yaffs_attribs.o
#	yaffs2-y += yaffs_yaffs1.o
#	yaffs2-y += yaffs_yaffs2.o
#	yaffs2-y += yaffs_verify.o
#	yaffs2-y += yaffs_summary.o

	yaffs2multi-y := yaffs_mtdif_multi.o
	yaffs2multi-y += yaffs_packedtags1.o
	yaffs2multi-y += yaffs_ecc.o yaffs_vfs_multi.o yaffs_guts.o
	yaffs2multi-y += yaffs_packedtags2.o
	yaffs2multi-y += yaffs_tagscompat.o
	yaffs2multi-y += yaffs_tagsmarshall.o
	yaffs2multi-y += yaffs_checkptrw.o yaffs_nand.o
	yaffs2multi-y += yaffs_checkptrw.o yaffs_nand.o yaffs_nameval.o
	yaffs2multi-y += yaffs_allocator.o yaffs_bitmap.o yaffs_attribs.o
	yaffs2multi-y += yaffs_yaffs1.o
	yaffs2multi-y += yaffs_yaffs2.o
	yaffs2multi-y += yaffs_verify.o
	yaffs2multi-y += yaffs_summary.o
