/*
 * reg_gp.h- Sigmastar
 *
 * Copyright (c) [2019~2020] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef _DSP_REG_GP_H_
#define _DSP_REG_GP_H_

#define DSP_GP_RESET       REG_ID_00
#define DSP_GP_RESET_ALL   BITS(7 : 0, BIT(0))
#define DSP_GP_RESET_CORE  BITS(7 : 0, BIT(1))
#define DSP_GP_RESET_RIU   BITS(7 : 0, BIT(2))
#define DSP_GP_RESET_RSVD  BITS(7 : 0, BIT(3))
#define DSP_GP_RESET_CORE0 BITS(7 : 0, BIT(4))
#define DSP_GP_RESET_CORE1 BITS(7 : 0, BIT(5))
#define DSP_GP_RESET_CORE2 BITS(7 : 0, BIT(6))
#define DSP_GP_RESET_CORE3 BITS(7 : 0, BIT(7))
#define DSP_GP_RESET_MASK  BMASK(7 : 0)

#define DSP_GP_VQ7_CLK_GATE            REG_ID_00
#define DSP_GP_VQ7_CLK_GATE_CORE0      BITS(11 : 8, BIT(0))
#define DSP_GP_VQ7_CLK_GATE_CORE1      BITS(11 : 8, BIT(1))
#define DSP_GP_VQ7_CLK_GATE_CORE2      BITS(11 : 8, BIT(2))
#define DSP_GP_VQ7_CLK_GATE_CORE3      BITS(11 : 8, BIT(3))
#define DSP_GP_VQ7_CLK_GATE_CORE0_MASK BMASK(8 : 8)
#define DSP_GP_VQ7_CLK_GATE_CORE1_MASK BMASK(9 : 9)
#define DSP_GP_VQ7_CLK_GATE_CORE2_MASK BMASK(10 : 10)
#define DSP_GP_VQ7_CLK_GATE_CORE3_MASK BMASK(11 : 11)
#define DSP_GP_VQ7_CLK_GATE_MASK       BMASK(11 : 8)

#define DSP_GP_VQ7_CLK_INV            REG_ID_00
#define DSP_GP_VQ7_CLK_INV_CORE0      BITS(15 : 12, BIT(0))
#define DSP_GP_VQ7_CLK_INV_CORE1      BITS(15 : 12, BIT(1))
#define DSP_GP_VQ7_CLK_INV_CORE2      BITS(15 : 12, BIT(2))
#define DSP_GP_VQ7_CLK_INV_CORE3      BITS(15 : 12, BIT(3))
#define DSP_GP_VQ7_CLK_INV_CORE0_MASK BMASK(12 : 12)
#define DSP_GP_VQ7_CLK_INV_CORE1_MASK BMASK(13 : 13)
#define DSP_GP_VQ7_CLK_INV_CORE2_MASK BMASK(14 : 14)
#define DSP_GP_VQ7_CLK_INV_CORE3_MASK BMASK(15 : 15)
#define DSP_GP_VQ7_CLK_INV_MASK       BMASK(15 : 12)

#define DSP_GP_VQ7_DFS_CORE0          REG_ID_01
#define DSP_GP_VQ7_DFS_CORE0_EN       BITS(5 : 5, BIT(0))
#define DSP_GP_VQ7_DFS_CORE0_CFG_MASK BMASK(4 : 0)
#define DSP_GP_VQ7_DFS_CORE0_CFG_LSB  0
#define DSP_GP_VQ7_DFS_CORE0_EN_MASK  BMASK(5 : 5)

#define DSP_GP_VQ7_DFS_CORE1          REG_ID_01
#define DSP_GP_VQ7_DFS_CORE1_EN       BITS(13 : 13, BIT(0))
#define DSP_GP_VQ7_DFS_CORE1_CFG_MASK BMASK(12 : 8)
#define DSP_GP_VQ7_DFS_CORE1_CFG_LSB  8
#define DSP_GP_VQ7_DFS_CORE1_EN_MASK  BMASK(13 : 13)

#define DSP_GP_VQ7_DFS_CORE2          REG_ID_02
#define DSP_GP_VQ7_DFS_CORE2_EN       BITS(5 : 5, BIT(0))
#define DSP_GP_VQ7_DFS_CORE2_CFG_MASK BMASK(4 : 0)
#define DSP_GP_VQ7_DFS_CORE2_CFG_LSB  0
#define DSP_GP_VQ7_DFS_CORE2_EN_MASK  BMASK(5 : 5)

#define DSP_GP_VQ7_DFS_CORE3          REG_ID_02
#define DSP_GP_VQ7_DFS_CORE3_EN       BITS(13 : 13, BIT(0))
#define DSP_GP_VQ7_DFS_CORE3_CFG_MASK BMASK(12 : 8)
#define DSP_GP_VQ7_DFS_CORE3_CFG_LSB  8
#define DSP_GP_VQ7_DFS_CORE3_EN_MASK  BMASK(13 : 13)

#define DSP_GP_TOP_CLK_CTRL              REG_ID_03
#define DSP_GP_TOP_CLK_CTRL_GATE_EN      BITS(0 : 0, BIT(0))
#define DSP_GP_TOP_CLK_CTRL_GATE_EN_MASK BMASK(0 : 0)
#define DSP_GP_TOP_CLK_CTRL_CLK_INV      BITS(1 : 1, BIT(0))
#define DSP_GP_TOP_CLK_CTRL_CLK_INV_MASK BMASK(1 : 1)
#define DSP_GP_TOP_CLK_CTRL_CLK_SEL_FAST BITS(3 : 2, 0)
#define DSP_GP_TOP_CLK_CTRL_CLK_SEL_SLOW BITS(3 : 2, BIT(0))
#define DSP_GP_TOP_CLK_CTRL_CLK_SEL_MASK BMASK(3 : 2)
#define DSP_GP_TOP_CLK_CTRL_MASK         BMASK(3 : 0)

#define DSP_GP_GPIO_CORE0 BITS(1 : 0, 0)
#define DSP_GP_GPIO_CORE1 BITS(1 : 0, BIT(0))
#define DSP_GP_GPIO_CORE2 BITS(1 : 0, BIT(1))
#define DSP_GP_GPIO_CORE3 BITS(1 : 0, (BIT(0) | BIT(1)))

#define DSP_GP_GPIO_SEL0        REG_ID_04
#define DSP_GP_GPIO_SEL0_LSHIFT 0
#define DSP_GP_GPIO_SEL0_MASK   BMASK(1 : 0)

#define DSP_GP_GPIO_SEL1        REG_ID_04
#define DSP_GP_GPIO_SEL1_LSHIFT 2
#define DSP_GP_GPIO_SEL1_MASK   BMASK(3 : 2)

#define DSP_GP_GPIO_SEL2        REG_ID_04
#define DSP_GP_GPIO_SEL2_LSHIFT 4
#define DSP_GP_GPIO_SEL2_MASK   BMASK(5 : 4)

#define DSP_GP_GPIO_SEL3        REG_ID_04
#define DSP_GP_GPIO_SEL3_LSHIFT 6
#define DSP_GP_GPIO_SEL3_MASK   BMASK(7 : 6)

#define DSP_GP_JTAG_SEL      REG_ID_04
#define DSP_GP_JTAG_CORE0    BITS(9 : 8, 0)
#define DSP_GP_JTAG_CORE1    BITS(9 : 8, BIT(0))
#define DSP_GP_JTAG_CORE2    BITS(9 : 8, BIT(1))
#define DSP_GP_JTAG_CORE3    BITS(9 : 8, (BIT(0) | BIT(1)))
#define DSP_GP_JTAG_SEL_MASK BMASK(9 : 8)

#define DSP_GP_TEST_BUS_SEL      REG_ID_04
#define DSP_GP_TEST_BUS_SEL_MASK BMASK(15 : 11)

#define DSP_GP_FORCE_ALL_SRAM_ON      REG_ID_05
#define DSP_GP_FORCE_ALL_SRAM_ON_EN   BITS(0 : 0, BIT(0))
#define DSP_GP_FORCE_ALL_SRAM_ON_MASK BMASK(0 : 0)

#define DSP_GP_CORE_SRAM_POWER            REG_ID_05
#define DSP_GP_CORE_SRAM_POWER_LSB        8
#define DSP_GP_CORE_SRAM_POWER_CORE0_MASK BMASK(8 : 8)
#define DSP_GP_CORE_SRAM_POWER_CORE1_MASK BMASK(9 : 9)
#define DSP_GP_CORE_SRAM_POWER_CORE2_MASK BMASK(10 : 10)
#define DSP_GP_CORE_SRAM_POWER_CORE3_MASK BMASK(11 : 11)
#define DSP_GP_CORE_SRAM_POWER_MASK       BMASK(15 : 8)

#define DSP_GP_CORE_PG_SRAM_POWER            REG_ID_06
#define DSP_GP_CORE_PG_SRAM_POWER_LSB        0
#define DSP_GP_CORE_PG_SRAM_POWER_CORE0_MASK BMASK(0 : 0)
#define DSP_GP_CORE_PG_SRAM_POWER_CORE1_MASK BMASK(1 : 1)
#define DSP_GP_CORE_PG_SRAM_POWER_CORE2_MASK BMASK(2 : 2)
#define DSP_GP_CORE_PG_SRAM_POWER_CORE3_MASK BMASK(3 : 3)
#define DSP_GP_CORE_PG_SRAM_POWER_MASK       BMASK(7 : 0)

#define DSP_GP_CORE_SRAM_SLEEP            REG_ID_06
#define DSP_GP_CORE_SRAM_SLEEP_LSB        8
#define DSP_GP_CORE_SRAM_SLEEP_CORE0_MASK BMASK(8 : 8)
#define DSP_GP_CORE_SRAM_SLEEP_CORE1_MASK BMASK(9 : 9)
#define DSP_GP_CORE_SRAM_SLEEP_CORE2_MASK BMASK(10 : 11)
#define DSP_GP_CORE_SRAM_SLEEP_CORE3_MASK BMASK(11 : 11)
#define DSP_GP_CORE_SRAM_SLEEP_MASK       BMASK(15 : 8)

#define DSP_GP_CORE_SRAM_DEEP_SLEEP            REG_ID_07
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_LSB        0
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_CORE0_MASK BMASK(0 : 0)
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_CORE1_MASK BMASK(1 : 1)
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_CORE2_MASK BMASK(2 : 2)
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_CORE3_MASK BMASK(3 : 3)
#define DSP_GP_CORE_SRAM_DEEP_SLEEP_MASK       BMASK(7 : 0)

#define DSP_GP_CORE_POWER            REG_ID_08
#define DSP_GP_CORE_POWER_LSB        0
#define DSP_GP_CORE_POWER_CORE0_MASK BMASK(0 : 0)
#define DSP_GP_CORE_POWER_CORE1_MASK BMASK(1 : 1)
#define DSP_GP_CORE_POWER_CORE2_MASK BMASK(2 : 2)
#define DSP_GP_CORE_POWER_CORE3_MASK BMASK(3 : 3)
#define DSP_GP_CORE_POWER_MASK       BMASK(7 : 0)

#define DSP_GP_CORE_ISOLATION            REG_ID_08
#define DSP_GP_CORE_ISOLATION_LSB        8
#define DSP_GP_CORE_ISOLATION_CORE0_MASK BMASK(8 : 8)
#define DSP_GP_CORE_ISOLATION_CORE1_MASK BMASK(9 : 9)
#define DSP_GP_CORE_ISOLATION_CORE2_MASK BMASK(10 : 10)
#define DSP_GP_CORE_ISOLATION_CORE3_MASK BMASK(11 : 11)
#define DSP_GP_CORE_ISOLATION_MASK       BMASK(15 : 8)

#define DSP_GP_CORE_MTCMOS      REG_ID_14
#define DSP_GP_CORE_MTCMOS_MASK BMASK(7 : 0)

#define DSP_GP_TEST_OUT_W      REG_ID_15
#define DSP_GP_TEST_OUT_W_MASK BMASK(23 : 0)

#endif /*_DSP_REG_GP_H_*/