#ifndef _KDRV_TGE_INT_H_
#define _KDRV_TGE_INT_H_

#include "kdrv_videocapture/kdrv_tge.h"

typedef ER (*KDRV_TGE_SET_FP)(UINT32, void*);
typedef ER (*KDRV_TGE_GET_FP)(UINT32, void*);

#define KDRV_TGE_VDHD_CH_ALL 	((1 << KDRV_TGE_VDHD_CH_MAX) - 1)	// (KDRV_TGE_VDHD_CH_1 | KDRV_TGE_VDHD_CH_2)
#define KDRV_TGE_SWAP_CH_ALL 	((1 << KDRV_TGE_SWAP_CH_MAX) - 1)	// (KDRV_TGE_SWAP_CH15 | KDRV_TGE_SWAP_CH26 | KDRV_TGE_SWAP_CH37 | KDRV_TGE_SWAP_CH48)
#define KDRV_TGE_SIE_VD_SRC_CH_ALL 	((1 << KDRV_TGE_SIE_SRC_CH_MAX) - 1)	// (KDRV_TGE_SIE1_IN | KDRV_TGE_SIE3_IN)
#define KDRV_TGE_CLK_ID_ALL 	((1 << KDRV_TGE_CLK_ID_MAX) - 1)	// (KDRV_TGECLK1 | KDRV_TGECLK2)

/**
	tge kdrv channel
*/
typedef enum {
	KDRV_TGE_UPDATE_BIT_BASE_VDHD_PARAM = 0,
	KDRV_TGE_UPDATE_BIT_BASE_VDHD_BP 	= (KDRV_TGE_UPDATE_BIT_BASE_VDHD_PARAM 	+ 8),
	KDRV_TGE_UPDATE_BIT_BASE_VDHD_SWAP 	= (KDRV_TGE_UPDATE_BIT_BASE_VDHD_BP 	+ 8),
	KDRV_TGE_UPDATE_BIT_BASE_MSH_CTRL 	= (KDRV_TGE_UPDATE_BIT_BASE_VDHD_SWAP 	+ 4),
	KDRV_TGE_UPDATE_BIT_BASE_FLSH_CTRL 	= (KDRV_TGE_UPDATE_BIT_BASE_MSH_CTRL 	+ 4),
} KDRV_TGE_UPDATE_BIT_BASE;

/**
    KDRV TGE structure
*/
typedef struct _KDRV_TGE_PRAM {
	KDRV_TGE_ISRCB isrcb_fp;
    KDRV_TGE_VDHD_INFO vdhd_info[KDRV_TGE_VDHD_CH_MAX];
    KDRV_TGE_BP_INFO tge_bp[KDRV_TGE_VDHD_CH_MAX];
	KDRV_TGE_SWAP_INFO tge_swap_vdhd_pin[KDRV_TGE_SWAP_CH_MAX];
	KDRV_TGE_TIMING_PAUSE_INFO tge_pause[KDRV_TGE_VDHD_CH_MAX];
	KDRV_TGE_SIE_VD_INFO tge_to_sie_vd_ch[KDRV_TGE_SIE_SRC_CH_MAX];
	KDRV_TGE_CLK_SRC_SEL tge_clk[KDRV_TGE_CLK_ID_MAX];
} KDRV_TGE_PRAM, *pKDRV_TGE_PRAM;

#endif //_KDRV_IME_INT_H_

