
obj-$(CONFIG_ARCH_GK710X) += gk710x.o
obj-$(CONFIG_ARCH_GK710X) += irq.o
obj-$(CONFIG_ARCH_GK710X) += rct.o
obj-$(CONFIG_ARCH_GK710X) += mdma.o dma.o
obj-$(CONFIG_ARCH_GK710X) += vi.o

obj-$(CONFIG_ARCH_GK710X)	+= mach-gk710x.o

ccflags-$(CONFIG_ARCH_GK710X) += -D__LINUX__ 

ccflags-$(CONFIG_ARCH_GK710X) += -Iarch/arm/mach-gk710x/include

