#
# Makefile for Xmedia processors family
#

obj-$(CONFIG_ARCH_XM72050200) += mach-xm72050200.o
obj-$(CONFIG_ARCH_XM72050300) += mach-xm72050300.o
obj-$(CONFIG_ARCH_XM72020300) += mach-xm72020300.o
obj-$(CONFIG_ARCH_XM76050100) += mach-xm76050100.o
obj-$(CONFIG_ARCH_XM72050500) += mach-xm72050500.o
obj-$(CONFIG_ARCH_XM720XXX) += mach-xm720xxx.o
