# File: drivers/net/arm/Makefile
#
# Makefile for the ARM network device drivers
#

ifdef CONFIG_ETH_GOKE
obj-$(CONFIG_GK_ETH_EMAC_V1_00)	+= gk_eth_v1_00.o
obj-$(CONFIG_GK_ETH_EMAC_V1_01)	+= gk_eth_v1_01.o
endif
