obj-$(CONFIG_VIDEO_AK)          := akcamera.o
akcamera-objs                   += ak_camera.o ak_sensor.o

obj-$(CONFIG_AK_SENSOR_I2C)	  += ak_sensor_i2c.o

obj-$(CONFIG_AK_SENSOR_COMMON)	+= ak_sensor_common.o

# sensor 
obj-$(CONFIG_SENSOR_AR0130)	  += sensor_ar0130.o

obj-$(CONFIG_SENSOR_BF3703)	  += sensor_bf3703.o

obj-$(CONFIG_SENSOR_F22_F23_F28_F35_F37) += sensor_f22+f23+f28+f35+f37.o

obj-$(CONFIG_SENSOR_GC1054)	  += sensor_gc1054.o

obj-$(CONFIG_SENSOR_GC2053)	  += sensor_gc2053.o

obj-$(CONFIG_SENSOR_H63)	  += sensor_H63.o

obj-$(CONFIG_SENSOR_H65)	  += sensor_h65.o

obj-$(CONFIG_SENSOR_IMX307)	  += sensor_imx307.o

obj-$(CONFIG_SENSOR_PS5260)	  += sensor_ps5260.o

obj-$(CONFIG_SENSOR_SC1235)	  += sensor_sc1235.o

obj-$(CONFIG_SENSOR_SC1245)	  += sensor_sc1245.o

obj-$(CONFIG_SENSOR_SC2232H_SC2135E)	  += sensor_sc2232h_sc2135e.o

obj-$(CONFIG_SENSOR_SC2235)	  += sensor_sc2235.o

obj-$(CONFIG_SENSOR_SC2239_SC2332_SC2335)	  += sensor_SC2239+SC2332+SC2335.o

obj-$(CONFIG_SENSOR_SP2305)	  += sensor_sp2305.o






