#ifndef _MTR_DTSI_H_
#define _MTR_DTSI_H_

#define MTR_DTSI_NAME_LENGTH    256
#define MTR_NODE_NAME_LENGTH    24


typedef enum _MTR_DTSI_ITEM {
	MTR_DTSI_SPI_TYPE,
	MTR_DTSI_SPI_CHNEL,
	MTR_DTSI_SPI_MODE,
	MTR_DTSI_SPI_PACKET_BIT,
	MTR_DTSI_SPI_BRAUD_RATE,
	MTR_DTSI_SPI_DATA_ORDER,
	MTR_DTSI_SPI_CS_POLARITY,
	MTR_DTSI_SPI_PACKET_DLY,

	MTR_DTSI_I2C_ID,
	MTR_DTSI_I2C_ADDR,

	MTR_DTSI_SPI_GPIO_CS,
	MTR_DTSI_SPI_GPIO_CLK,
	MTR_DTSI_SPI_GPIO_TX,
	MTR_DTSI_SPI_GPIO_RX,

	MTR_DTSI_PWM_MODE,
	MTR_DTSI_PWM_FOCUS_FREQ,
	MTR_DTSI_PWM_ZOOM_FREQ,
	MTR_DTSI_PWM_FOCUS_PORT_SEL,
	MTR_DTSI_PWM_ZOOM_PORT_SEL,

	MTR_DTSI_GPIO_RST_PIN,
	MTR_DTSI_GPIO_PWDN_PIN,
	MTR_DTSI_GPIO_FZ_VD_PIN,
	MTR_DTSI_GPIO_IS_VD_PIN,
	MTR_DTSI_GPIO_FOCUS_STS_PIN,
	MTR_DTSI_GPIO_ZOOM_STS_PIN,
	MTR_DTSI_GPIO_IRCUT_0_PIN,
	MTR_DTSI_GPIO_IRCUT_1_PIN,
	MTR_DTSI_GPIO_EXT_0_PIN,
	MTR_DTSI_GPIO_EXT_1_PIN,
	MTR_DTSI_GPIO_EXT_2_PIN,
	MTR_DTSI_GPIO_EXT_3_PIN,

	MTR_DTSI_LENS_WIDE_FOCAL,
	MTR_DTSI_LENS_TELE_FOCAL,
	MTR_DTSI_LENS_FOCUS_POS_DIR,
	MTR_DTSI_LENS_ZOOM_POS_DIR,
	MTR_DTSI_LENS_FOCUS_INIT_OFST,
	MTR_DTSI_LENS_ZOOM_INIT_OFST,
	MTR_DTSI_LENS_FOCUS_DIS_MAX,
	MTR_DTSI_LENS_ZOOM_DIS_MAX,
	MTR_DTSI_LENS_FOCUS_MOVE_SPD,
	MTR_DTSI_LENS_ZOOM_MOVE_SPD,
	MTR_DTSI_LENS_FOCUS_BACKLASH,
	MTR_DTSI_LENS_ZOOM_BACKLASH,
	MTR_DTSI_LENS_FOCUS_DLY_TIME,
	MTR_DTSI_LENS_ZOOM_DLY_TIME,
	MTR_DTSI_LENS_FZ_TAB0,
	MTR_DTSI_LENS_FZ_TAB1,
	MTR_DTSI_LENS_FZ_TAB2,
	MTR_DTSI_LENS_FZ_TAB3,
	MTR_DTSI_LENS_FZ_TAB4,
	MTR_DTSI_LENS_FZ_TAB5,
	MTR_DTSI_LENS_FZ_TAB6,
	MTR_DTSI_LENS_FZ_TAB7,
	MTR_DTSI_LENS_FZ_TAB8,
	MTR_DTSI_LENS_FZ_TAB9,
	MTR_DTSI_LENS_FZ_TAB10,
	MTR_DTSI_ITEM_MAX_NUM,
	ENUM_DUMMY4WORD(MTR_DTSI_ITEM)
} MTR_DTSI_ITEM;


typedef struct _MTR_DTSI_INFO {
	CHAR node_path[MTR_DTSI_NAME_LENGTH];
	CHAR file_path[MTR_DTSI_NAME_LENGTH];
	UINT8 *buf_addr;
} MTR_DTSI_INFO;

typedef struct _MTR_DTSI_FILE {
	CHAR node_name[MTR_NODE_NAME_LENGTH];
	CHAR data_name[MTR_NODE_NAME_LENGTH];
	UINT8 *pdata;
	INT32 size;
} MTR_DTSI_FILE;

typedef struct _MTR_DTSI {
	CHAR item_name[MTR_NODE_NAME_LENGTH];
	CHAR data_name[MTR_NODE_NAME_LENGTH];
	UINT32 tmp_buf;
} MTR_DTSI;


#endif

