obj-y                   := core.o clock.o timer.o
obj-$(CONFIG_SMP)           += platsmp.o headsmp.o
obj-$(CONFIG_HOTPLUG_CPU)       += hotplug.o
obj-$(CONFIG_CACHE_L2X0)        += l2cache.o
obj-$(CONFIG_DMA_ENGINE) += dma.o

