
#ifndef __USB_CHRGDET_REG_H__
#define __USB_CHRGDET_REG_H__

#include "mach/rcw_macro.h"
#include "kwrap/type.h"



REGDEF_OFFSET(USB3APB_CHARGER_CONTROL_REG, 0x00)
REGDEF_BEGIN(USB3APB_CHARGER_CONTROL_REG)
REGDEF_BIT(DCD_DETECT_EN, 1)
REGDEF_BIT(SECOND_CHG_DETECT_EN, 1)
REGDEF_BIT(CHG_DETECT_EN, 1)
REGDEF_BIT(, 29)
REGDEF_END(USB3APB_CHARGER_CONTROL_REG)

REGDEF_OFFSET(USB3APB_BUS_STATUS_REG, 0x08)
REGDEF_BEGIN(USB3APB_BUS_STATUS_REG)
REGDEF_BIT(, 6)
REGDEF_BIT(CHG_DET, 1)
REGDEF_BIT(, 25)
REGDEF_END(USB3APB_BUS_STATUS_REG)





#define USB_CHARGER_CONTROL_REG_OFS     0x300
REGDEF_BEGIN(USB_CHARGER_CONTROL_REG)
REGDEF_BIT(DCD_DETECT_EN, 1)
REGDEF_BIT(CHG_DETECT_EN, 1)
REGDEF_BIT(SECOND_CHG_DETECT_EN, 1)
REGDEF_BIT(, 29)
REGDEF_END(USB_CHARGER_CONTROL_REG)

#define USB_BUS_STATUS_REG_OFS          0x308
REGDEF_BEGIN(USB_BUS_STATUS_REG)
REGDEF_BIT(, 6)
REGDEF_BIT(CHG_DET, 1)
REGDEF_BIT(, 25)
REGDEF_END(USB_BUS_STATUS_REG)


#endif
